AxFoundation/strax

- requirements.txt
If you pin versions, it will make things in the long run easier for reproducibility.  Also, we make sure that we are testing the same versions that we are deploying.
> Pin requirements.txt

- setup.py
Instead of repeating the requirements, you can just read requirements.txt then strip pinned versions.  See #6
> Avoid repeating requirements

- strax/xenon/pax_interface.py
This should fix the pax conversion error #39 due to the presence of trigger monitor data zips. Not tested. Only works for TPC names that start with XENON.
> Pax conversion: load only true zip files

- strax/mailbox.py
For processing, it's useful to be able to specify the timeout.  In this case, it's a global variable in mailbox.  This way, processing can overload this before initializing strax.
> Make Mailbox timeout a variable

- strax/mailbox.py
Allows overloading mailbox size instead of hard codes.  You have to set the variable before initializing strax.
> Add global variable for configuring mailbox size

- strax/storage/s3.py
Same thing as before but with a new schema.  Instead of each bucket being a strax key, all objects live in one bucket.  Instead of buckets, I use 'folders' (i.e. key is strax_key/chunk_id).  This seems to be the right way to go.  Once this merges and goes into a release, I'll start using this as the main backend at the moment for XENON data at least.
Also, factor out JSON uploader to S3.
> Redo S3 schema (use one Bucket due to limited number of buckets

- strax/plugin.py
- strax/processing/general.py
- tests/test_general_processing.py
- tests/test_overlap_plugin.py
This fixes two edge cases that our randomized testing sometimes flags: #49 and #37. This also includes explicit examples of the underlying problems in the test suite -- so if these problems arise again, we will get build failures every time.
> Fix processing algorithm edge cases

- strax/context.py
- tests/test_core.py
This disables any attempted data saving (with a warning) while the user has fuzzy matching or time range selection options turned on.
Saving when fuzzy matching is turned on is particularly dangerous (thanks @coderdj for pointing this out) because it would produce wrongly tagged data. In principle we could deduce the correct lineage/config from the loaded data, but this becomes quite complicated. For now, disallowing it is safer.
Saving during time range selection is already impossible normally, since time range selection requires the data to be available already. However, it could occur happen when the storage conversion mode was turned on. If so, we would have produced incomplete data that only has the requested time range saved.
> Do not save during time range selection and fuzzy matching

- strax/xenon/pax_interface.py
- strax/xenon/plugins.py
Pax data was mistakenly rechunked upon conversion to the strax format, causing errors in later processing (specifically `event_basics`, or probably any `LoopPlugin` subclass). This fixes the problem.
One more change: peaks' output is now also rechunked to more convenient file sizes. I found this significantly speeds up processing that starts from peaks. Unfortunately it has no effect on full-chain processing, since rechunking currently only affects saving (I'll make an issue for this)
> Fix pax conversion

- setup.py
- strax/storage/s3.py
- strax/xenon/__init__.py
- strax/xenon/rundb.py
(This is XENON-specific, still need to do #48)
This addresses Issue #73.  There is a frontend that looks for data in a run database.  Currently, no default is given, so the MongoURL has to be fed in.  For example:
```
import strax
st = strax.Context(
storage=strax.xenon.RunDB(mongo_url='mongodb://rundb-rw:XXXXX@rundbcluster-shard-00-00-cfaei.gcp.mongodb.net:27017,rundbcluster-shard-00-01-cfaei.gcp.mongodb.net:27017,rundbcluster-shard-00-02-cfaei.gcp.mongodb.net:27017/test?ssl=true&replicaSet=RunDBCluster-shard-0&authSource=admin&retryWrites=true'),
register_all=strax.xenon.plugins,
register=strax.xenon.pax_interface.RecordsFromPax
)
d = st.get_array('170321_0620', 'raw_records')
```
The way it works is by searching the RunDB for data of interest (this is the only RunDB call!).  If a run …
> XENON RunDB Frontend

- strax/plugin.py
- strax/processor.py
- tests/test_core.py
- tests/test_parallelsourceplugin.py
This adds tests for the ParallelSourcePlugin, and should fix issue #97. I think @coderdj originally hit this  issue during the Stockholm strax workshop, and @tunnell has been seeing it during the SR1 conversion.
ParallelSourcePlugins (see docs: https://strax.readthedocs.io/en/latest/developer/parallel.html#parallelsourceplugin) inline other plugins, so they have multiple outputs. They need an intermediate mailbox to stage these outputs to. Unfortunately, this mailbox was named after the original plugin, which clashed with the mailbox used for outputting the data the original plugin produced (e.g. raw_records). If that data was needed anywhere else, e.g. as the final target, strange stuff would happen.
I could not get my test to run with multiprocessing activated. Since multiprocessing …
> ParallelSourcePlugin fixes and test

- .gitignore
- notebooks/Online monitor demo.ipynb
- notebooks/eb.py
- notebooks/plots.py
- notebooks/visualization.ipynb
- strax/context.py
- strax/plugin.py
- strax/processor.py
- strax/storage/common.py
- strax/storage/files.py
- strax/storage/s3.py
- strax/storage/zipfiles.py
- strax/utils.py
- strax/xenon/cut_plugins.py
- strax/xenon/plugins.py
This includes the strax changes and notebooks used for the demonstration I gave at Coimbra. Specifically:
* A new context option `allow_incomplete`. If set, and the storage backend supports it, it will allow users to load data that has not yet been completely written. When set, all saving is blocked and generates a warning instead, just like for the fuzzy and time range options.
* Support for `allow_incomplete` in the files backend. To enable this, the files backend now writes metadata to disk every chunk, which may cause a tiny slowdown. If a forked saver is used to save the data (e.g. raw_records during DAQ reading) `allow_incomplete` will not work yet.
* Some extra validation of context options: you now get a warning if you specify an unknown option.
* Protection against a common …
> Load incomplete data, collaboration meeting demos

- .travis.yml
- requirements.txt
- strax/chunk_arrays.py
- strax/io.py
- strax/mailbox.py
- strax/plugin.py
- strax/processing/general.py
- strax/processing/peak_building.py
- strax/processing/peak_splitting.py
- strax/processing/pulse_processing.py
- strax/processor.py
- strax/storage/common.py
- strax/storage/files.py
- strax/storage/s3.py
- strax/utils.py
- tests/test_core.py
- tests/test_parallelsourceplugin.py
- tests/test_peak_processing.py
This contains several bugfixes discovered during the test of the new DAQ, described in the individual commits. Several of these came to light only now due to the somewhat "interesting" waveforms seen in the initial data. 
I will likely add to this during this week.
> Bugfixes from the DAQ test

- strax/processing/peak_building.py
- strax/processing/peak_properties.py
- strax/utils.py
Errors appeared in a rare situation where the zero-padded part of a record overlaps with a peak, causing a nonphysical selection range. 'Lucky'  enough this situation was not so rare in XAMS-type data :) I believe the right behavior is a ''continue'' meaning to skip this record in the peak consideration.
> Several bugfixes in peak processing

- strax/storage/common.py
- strax/storage/files.py
- strax/storage/zipfiles.py
- tests/test_core.py
My suggestion is to adjust the XENONnT naming convention to get unique file names. My implementation takes the information about the file name convention simply from directory (dirname) information at the level of the backend.
To get a clean solution we may improve later the frontend-backend communication to get all necessary from the database itself (or a similar interface).
I tested running a  simple STRAX script which processed several plugins on the fly to get a high-level dataframe back. The data structure looks good to me.
@JelleAalbers I choose to write the "more complicated" looking NameConvention class in order to be able to create a string from keywords with the freedom of simply handing dictionaries over to fill out such keywords (similar to *.format() in Python) but do not …
> Adjust file naming convention

- strax/plugin.py
- strax/utils.py
This replaces the algorithm by which strax computes the hash of the data lineage. Since the hash is part of the key for looking up data, it has implications for previously produced strax data.
Changes to hash algorithm
-----------------------------
1. Instead of ` pickle.dumps(x)`, `json.encode(x, sort_keys=True).encode('ascii')` is used to transform the lineage into bytes (after converting it to immutables, i.e. lists -> tuples). We found out pickle's output can depend on the reference counting of the objects to be hashed (see [here](https://stackoverflow.com/questions/45015180) and [here](http://www.aminus.org/blogs/index.php/2007/11/03/pickle_dumps_not_suitable_for_hashing?blog=2)). This would have meant, for example, that future strax versions might not have found data created by past …
> Stabilize and shorten lineage hash 

- requirements.txt
- strax/context.py
- strax/storage/common.py
- strax/storage/files.py
- strax/storage/zipfiles.py
- strax/utils.py
- tests/test_core.py
This generalizes and improves the run selection and multi-run loading support from straxen, and moves it to strax. Specifically:
* Support for loading/creating data for multiple runs at a time with `get_df`, `get_array` and `make`: simply pass a list/tuple of runids. An extra `run_id` field will be added to the output dataframe/array so you can track which events came from which runs.
* New `select_runs` and `scan_runs` context methods, ported from straxen. `scan_runs` is the important one: it populates a dataframe with basic run info, from run-level metadata (run docs) provided by the storage frontends (through their `_scan_runs` and `list_available` methods). `select_runs` just contains some helpers for making selections on this dataframe based on tags and run mode fields.
* The …
> Run selection and run-level metadata handling, multi-run loading

- README.md
- strax/context.py
- strax/processing/data_reduction.py
- strax/processing/peak_building.py
- strax/processing/pulse_processing.py
- tests/test_pulse_processing.py
* Add `zero_outside_bounds`, which sets record waveforms to zero where they do not represent real data. For example, for 100-sample pulse stored in a 110-sample record, it will zero the final ten samples. Not doing this (and instead relying on the DAQ + `strax.baseline` to do it) may have contributed to some problems with the data reduction algorithms we saw during the latest DAQ test.
* Add `filter_records`, which allows linear filtering of waveforms, e.g. to improve signal/noise or sharpen the pulses for better data reduction. It takes account of the fact that pulses are split over multiple records, by applying the convolution multiple times with different filter shifts (for the parts of the record for which this is needed). The convolutions is applied outside of numba, using …
> Pulse processing upgrades

- strax/__init__.py
- strax/storage/mongo.py
Started with a mongodb store that Jelle wrote then removed from strax ~1 year ago and updated it to the frontend/backend/saver paradigm. It's for use in the online monitoring where some basic plugins will dump info to MongoDB for display online.
> MongoDB Output

- strax/mailbox.py
- strax/processor.py
- strax/storage/common.py
- tests/test_core.py
This makes strax crash if an exception occurs while saving data. Previously such exceptions could only be recovered from the metadata of the data type whose saver crashed, since the strax processing command itself just succeeded.
* An exception in the saver now gets thrown inside the mailbox it is reading from. This will kill now the mailbox, which as before brings down the whole processing and reraises the original exception at the end.
* When the exception occurs at the very end of processing, this isn't enough, since Mailbox._read passes beyond the logic capable of handling exceptions when the last message is delivered. Thus, we also store the exception in a new attribute `got_exception` of the saver. At the end of processing, we check if any of the savers have this attribute set, and …
> Saver exception handling

- docs/source/reference/strax.storage.rst
- strax/context.py
- strax/dtypes.py
- strax/mailbox.py
- strax/processing/peak_building.py
- strax/storage/files.py
- strax/utils.py
- tests/test_peak_processing.py
* Change the area_per_channel field of peaks to be in PE, to ensure fewer plugins need to know about the PMT gains.
* Replace `min_hits` with `min_channels` as an option to `find_peaks`. When set to 2 or higher numbers, this will help cuts down the amount of peaks.
* Some misc reformatting / recommenting
> Area per channel in PE

- strax/context.py
allow for selection of data  set by giving one specific run_id and also it can  be used with matching a given numbers of run_ids (example: run_id="110*").
> fetch data sets based on run_id. Modif. in select_runs

- strax/context.py
- strax/plugin.py
- strax/processor.py
- strax/storage/common.py
- strax/storage/files.py
This removes an unused earlier implementation of data availability checking, and adds a small fix for ParallelSourcePlugin's with dependencies.
> Fixes for availability check, parallelsourceplugin

- strax/chunk_arrays.py
- strax/processor.py
- strax/utils.py
* If an output of a multi-output plugin isn't saved or used anywhere in the processing, it is discarded. This situation used to crash strax with an error about starting a mailbox without a subscriber.
* Fix to `chunk_arrays.py` to improve the behaviour for empty data (e.g. 'events' if the run has no events). I'm still not sure strax can fully handle this case, see #162.
* The strax.profile_threaded function now works also if you don't have `gil_load` installed. This is useful since `gil_load` doesn't always compile, and it is not essential for profiling.
> Three small fixes

- docs/source/advanced/superrun.rst
- docs/source/index.rst
- docs/source/reference/strax.processing.rst
- docs/source/reference/strax.rst
- docs/source/reference/strax.storage.rst
- requirements.txt
- strax/config.py
- strax/context.py
- strax/io.py
- strax/processing/data_reduction.py
- strax/processing/general.py
- strax/processing/peak_building.py
- strax/run_selection.py
- strax/storage/common.py
- strax/storage/files.py
- strax/utils.py
- tests/helpers.py
- tests/test_core.py
- tests/test_data_reduction.py
- tests/test_general_processing.py
- tests/test_peak_processing.py
Superruns
===============
A superrun is a run defined by (parts of) other runs, called 'subruns'. It is like a tag, but can be applied to parts of runs. Superruns can also be built from other superruns, enabling multiple levels of grouping. Details are in a new documentation page.
For example, `_rn_february`, `_sr1_background_v0.2`, or `_1234_lowenergyonly` might be superruns. Superrun ids start with an underscore. Regular run ids cannot start with an underscore from now on.
The two main uses are:
* Grouping runs to load high-level data faster and easier. A high-level datafile (e.g. event_info) for a single one-hour run is often a sub-MB file. If we have O(10^4) runs, as in XENON1T, loading these over a network filesystem is very time-consuming. Strax's detailed configuration checking …
> Superruns, LZ4, pulse processing fixes

- strax/plugin.py
- strax/processor.py
- strax/storage/files.py
- tests/test_overlap_plugin.py
As discovered by @jorana, strax's OverlapWindowPlugin crashes with an IndexError if an empty chunk is found in the data stream. In general strax is not very robust against this case (see #162), but we are improving.
You can read how OverlapWindowPlugin works [here](https://strax.readthedocs.io/en/latest/developer/overlaps.html#overlap-window-plugins). For an empty chunk, this PR changes strax to simply not send or discard any data; the input/output caches remain the same. The case of the last chunk (after which you must send everything even it if is empty) is already handled by the `iter` method. 
This escaped the property-based testing due to a spurious condition in the test (I guess I just didn't consider empty chunks would be possible) that is now removed.
(This also removes some old …
> Protect OverlapWindowPlugin against empty chunks

- .travis.yml
- strax/testutils.py
- tests/test_chunk_arrays.py
- tests/test_core.py
- tests/test_data_reduction.py
- tests/test_general_processing.py
- tests/test_helpers.py
- tests/test_multi_output.py
- tests/test_overlap_plugin.py
- tests/test_peak_processing.py
- tests/test_pulse_processing.py
- tests/test_utils.py
This cleans up strax' test helpers file, which contains mainly [hypothesis](https://hypothesis.works/) strategies for making random records and peaks for testing data processing routines.
There are now no side effects from importing it -- in particular, we no longer mock numba for performance during tests. This makes the tests take slightly longer, but only if the compilation cache is not present (e.g. on Travis or after changes). Since we use numba in production we should clearly also test with it. Also, since numba is considering using strax as an integration test (https://github.com/numba/numba-integration-testing/issues/29) I'm sure they would appreciate if we don't replace `sys.modules['numba']` with a MagicMock...
The test helpers file is made accessible as strax.testutils, since …
> Cleanup tests, make helpers accessible

- docs/source/advanced/plugin_dev.rst
- strax/__init__.py
- strax/config.py
- strax/context.py
- strax/run_selection.py
- strax/storage/files.py
- tests/test_core.py
This allows runs to specify default values for strax processing options via their metadata (run documents / database) using the `strax_defaults` field. This is very similar to the `processor...` field in XENON1T and will hopefully make correction handling a lot easier. Strax configruration priority is now as follows (high to low):
* Context options (set by user)
* Defaults specified in run metadata (i.e. run document/database)
* Defaults specified with plugin definition, using `default`, `default_factory` or `default_per_run` (in that order of priority).
The `default_per_run` option will soon be deprecated/removed , now that this new way of specifying run-dependent defaults is available. Currently `default_per_run` forces strax runs to have names that are castable to integers, which …
> Specify defaults via run metadata / run doc

- strax/processing/peak_building.py
Implementing gapsize clustering with two steps will require downsampling, upsampling, and downsampling again, since the sum_waveform will be constructed and saved for the "peaklets" and the "peaks". This separates the downsampling step as its own function for repeated/external use.
> Export downsample

- strax/context.py
- strax/dtypes.py
- strax/processing/peak_building.py
- strax/processing/peak_splitting.py
- tests/test_peak_processing.py
This adds support for variations of Jenks/Fischer natural breaks for splitting peaks, as an alternative to or replacement for the local minimum prominence finding algorithm method.
You can find some background info on [wikipedia](https://en.wikipedia.org/wiki/Jenks_natural_breaks_optimization) and [here](https://medium.com/analytics-vidhya/jenks-natural-breaks-best-range-finder-algorithm-8d1907192051). In computer vision, when used on an image intensity histogram, this is known as [Otsu's method](https://en.wikipedia.org/wiki/Otsu%27s_method). 
Natural breaks finds a point in the waveform that maximizes the 'goodness of split':
```
s(left)  +  s(right)
1  -  --------------------
s(original)     
```
Here s is the (weighted) sum squared deviation from the (weighted) mean, and 'left' and …
> Natural breaks splitting

- strax/context.py
- strax/plugin.py
- strax/storage/common.py
- strax/utils.py
- tests/test_core.py
This is a fix for #230, i.e. the treatment of the time_range / seconds_range / time_within options.
Background info:
* Strax supports (a) data without time information, such as `peaklet_classification` or `corrected_areas` and (b) data that is never stored, such as peaks, or the temporary datatypes that are made to merge e.g. `peaks` and `peak_basics` if you load them together.
* Strax even allows time selection with a no-time datatype as long as you load it alongside data of the same kind that does have time info (like `peaks`). It will then use the latter to map the time range to row numbers, which can be selected in the no-time datatypes.
There were two bugs:
* Strax was too coarse when converting time ranges to row numbers. We picked whichever time-bearing datatype was listed first, …
> Fix time range finding issues

- strax/dtypes.py
This restores the baseline field in raw_records as an int16 field. As @k-hiraide pointed out,  the neutron veto digitizers can report their online baseline estimates, and it would be a waste not to store this.
> Add baseline back into raw_records

- strax/chunk.py
For DAQ-purposes, printing the datarate can be helpfull information to add while chunking data.
> Print MB/s while chunking data

- strax/processing/pulse_processing.py
If input data to strax is sufficiently bad, we could miss the 0th record but have a later record of a pulse in a chunk. If this happens, and it is the first pulse in that channel, we currently accidentally assume a baseline of 0. This is bad since baselines are usually around 16000.
This makes strax throw an error instead in this situation. To allow processing of data that has been improperly chunked, `strax.baseline` gets the extra options `allow_sloppy_chunking` (default False) and `fallback_baseline` (default 16000). If `allow_sloppy_chunking=True`, we will use the `fallback_baseline` instead of throwing an error in the situation mentioned above.
> Check for presence of 0th fragment while baselining

- strax/io.py
This could be a very small change to add some extra info in to a ValueError arising from np.frombuffer.
This has proven to be useful after the latest strax(en) format change and sorting out if redax-output and strax(en) input are in sync.
> Add info to ValueErrors for np.frombuffer

- strax/context.py
- strax/mailbox.py
- strax/plugin.py
- strax/processor.py
- tests/test_mailbox.py
This makes strax's processing more robust and use 15-20% less memory when in single-core mode. Multicore processing is unchanged.
In the new mode, called 'lazy processing', a piece of data is only loaded or computed when it is requested by a higher-up plugin (or, ultimately, the user). Mailboxes now track who is waiting for what chunk. In lazy mode, they will:
* Block fetching of new messages if any subscriber is 'waiting' for a message we already have. This just means the OS hasn't given its thread priority yet.
* Fetch a new message only when a "driving" subscriber -- a plugins, not a saver -- is waiting for a new chunk we don't yet have.
This avoids loading chunks we do not need in memory, saving a bit of memory. More importantly, it means the buffers can be unbounded -- `max_messages` …
> Lazy mailbox

- strax/context.py
This is a great feature of strax that is needed if one e.g. wants to load only a small part of the data. The exception is also gread in case the RunMetaData is not available. 
However in case of incomplete RunMetaData the error is not a `strax.RunMetadataNotAvailable` but a `KeyError` since `'start'` is not in the RunMetaData. Hence I'd propose to also accept the `KeyError` as an exception.
I've tested in on eb0 for run 7157 and 7158 while loading raw_records with incomplete RunMetaData:
`` 
rr = st.get_array('007158', targets = ['raw_records'], seconds_range = (0,5))
``
> Make exception work for incomplete matadata too

- strax/mailbox.py
- strax/plugin.py
- strax/processor.py
This:
* Makes multi-output plugins respect lazy mode (#241). Currently `divide_outputs` doesn't account for lazy mode, so a multi-output plugin could still run away and fetch as much as it likes (potentially blowing up since in lazy mode, the max_messages limits are removed)
* For plugins with multiple inputs, the input controlling the chunk size ('pacemaker') is chosen to be the input that produces the smallest first chunk. Currently we just take the first dependency listed in depends_on.
* OverlapWindowPlugin no longer keeps one chunk back, since it is now OK to yield empty chunks.
These together reduce strax's memory usage in single-core mode by about 15-20%, on top of the similar reduction from #241. Lazy mode now uses about ~30% less memory than non-lazy mode.
The only downside of …
> More memory optimizations

- strax/storage/common.py
- strax/storage/files.py
This restores the ability to load incomplete data -- i.e. data that is still being built or whose build has crashed in a bad way. A before, to use it, just set `allow_incomplete=True` in the context config. 
For most datatypes (peaks, pulse_counts, etc) we only needed small fixes:
* Fix get_metadata to only look for the temporary (incomplete) metadata if the main file does not exist. Without this allow_incomplete would no longer allow you to load regular data.
* Write the start time into the metadata as soon as the first chunk arrives.
For datatypes with forked savers, such as records and raw_records during multiprocessing, things were and still are slightly trickier. To avoid having to think about race conditions, we initially write the metadata of each chunk to its own separate json …
> Fix loading of incomplete data

- strax/context.py
- strax/processor.py
*  When an exception inside `get_iter` occurs, it is now caught, submitted to the Processor (which kills all the mailboxes), and reraised. Currently these exceptions cause a hang instead (terminated by the mailbox timeout -- hopefully). After this, we will shut down cleanly and the proper exception will be recorded in the metadata.
* When an exception in code calling `get_iter` occurs, e.g. in the body of a for loop over `get_iter` (such as in `get_array`, or less trivially, in `straxer`), we don't get a chance to catch the exception. Instead, we will write a custom `OutsideException` to the metadata, with a message saying the exception originated from beyond strax's get_iter.
* If the for loop driving `get_iter` wants to do better than this, it would have to be wrapped in a try: except, …
> Exception handling fixes

- strax/processing/data_reduction.py
- strax/processing/pulse_processing.py
For late records in pulses longer than 32767 samples (327.67 us at 10 ns, 65.5 us at 2ns resolution), the computation
```python
len(record['data']) * record['record_i']
```
will result in an integer wraparound to negative values, since the record_i field is a 16 bit integer.
For the situations I tested, it seems this does NOT happen in numba compiled functions, only in pure numpy/python. So most of strax is safe. In any case, such long pulses should be pretty rare.
Nonetheless, I went through the code and removed places where we rely on this computation. There were several places where we  did `min(samples_per_record, pulse_length - record_i * record_length)`, but this is identically equal to `length`.
I also removed an unused and non-working data reduction function …
> Simplify length computations / protect from wraparounds

- requirements.txt
It is used here so might be good to add to the requirements: https://github.com/AxFoundation/strax/blob/master/strax/storage/common.py#L9
> Update requirements for packaging

- strax/dtypes.py
- strax/processing/peak_building.py
- strax/processing/pulse_processing.py
This adds the field `amplitude_bit_shift` to records, as introduced by @zhut19 in https://github.com/XENONnT/straxen/pull/38.  This will help make desaturation corrections possible, e.g. based on pulse shape as in XENON1T or using the attenuated / high-energy channels (@ariannarocchetti @petergaemers).
Setting this field means the amplitude the data should be multiplied by `2**amplitude_bit_shift` before it is used. Currently, desaturation corrections cannot store amplitudes above `2**15 -1`, since strax uses signed 16-bit integers (np.int16) to represent waveforms. After this, a correction function could set amplitude_bit_shift = 1 (or 2, 3, etc) and divide the whole waveform by 2 (or 4, 8, etc), so it can store higher amplitudes while staying within the allowed integer range. Of course …
> Add record amplitude bit shift

- strax/storage/common.py
Strax was supposed to cache lineage hashes for data keys -- it didn't, now it does.
> Fix lineage hash caching

- strax/processing/pulse_processing.py
Replaced (-1*flip) with np.where(flip, -1, 1) to fix flip=False bug in records flipping.
using np.where with flip as boolean, will return -1 if flip=True, else returns 1. 
Previously boolean meant if flip=False d['data'] will go to 0.
Also I believe that calculating https://github.com/AxFoundation/strax/blob/8e94cd95d823c1537cd49a568d8a3ee4e0204ea5/strax/processing/pulse_processing.py#L40
in baseline computation is unnecessary.
> fix flip boolean bug in pulse_processing

- strax/dtypes.py
- strax/plugin.py
- strax/processor.py
This allows a multi-output plugin to specify which of its output dtypes should be rechunked. You can set the `rechunk_on_save` attribute to:
* True: rechunk all outputs
* False: do not rechunk anything
* (immutable)dict mapping dtypes -> True/False, per-datatype control.
The main use case is [PulseProcessing](https://github.com/XENONnT/straxen/blob/446c388eb8411cf87aa7d8e54cc8520c1a599cc0/straxen/plugins/pulse_processing.py#L81) in straxen, which outputs small monitoring datatypes (pulse_counts, veto_regions) besides the big records dtype. We can't rechunk records since that would make their expensive saving operation non-parallelizable, but we should rechunk pulse_counts and veto_regions to avoid saving many 3 kB files that give rucio a headache.
> Per-datatype rechunking control

- strax/context.py
**Problem**
We forbid the creation of records if only raw_records is in the forbid_creation of. If we compare stings, 'records' is in 'raw_records'. 
yields the following error: 
This is not entirely correct, we just specified we couldn't create raw_records. 
**Solution/test**
This starts making 'records'
**Additional**
I don't think we want to allow users to create 'records' in straxen. As such I think we should specify that we forbid creation of ('raw_records', 'records') on line https://github.com/XENONnT/straxen/blob/master/straxen/contexts.py#L68.
> Fix error in forbid_creation_of

- strax/processing/peak_merging.py
For peaks with an endtime we need to recompute those numbers as otherwise we end up with a 0 as an `endtime `and `strax.endtime(peak)` will simply compute the endtime.
For example I tried merging peaks like these:
Which gave me this obviously wrong peak:
Maybe we should also change `strax.endtime `to not return `0`'s unless we consider going back in time to the 70s.
**Why haven't we seen this before**
Endtime is a field for peaks and higher while this code is only used for `peaklets`. Therefore we haven't run into this before but I foresee that solving issues that might arise might appear very strange if we want to remerge peaks at some point with strax.
> Fix endtimes in peaks merging

- strax/chunk.py
**Problem**
We observed that although the data is always sorted by (start)time, this is not per se true for the endtime. Therefore the last record may not have the latest endtime. We need to check this and not proceed if we observe such a thing. 
**Example**
As Daniel illustrated nicely. Image we have to following data where `-` means data, `_` means no data, and `|` means start and stop.
```
ch0: |---|__
ch1: _|-|___
```
Here the signal in ch0 starts before the signal in ch1 while the end of ch0 is __later__ than ch1. Hence we need to check both channels.
**Solution**
We used to look only at the last sample only but we need to look into the endtimes better to assert that we are not having any data sticking out of the chunk. This is the safest way to get around this (that is look at all …
> Correctly check endtimes in chunk.py

- docs/source/advanced/chunking.rst
- strax/chunk.py
- strax/context.py
- strax/plugin.py
- strax/storage/common.py
This changes the default uncompressed chunk size from 100 MB (specified in an obscure, undocumented location) to a plugin-definable value, with new default 200 MB. This value gets stored with the metadata, but if it's missing the default is assumed. This should affect writing data much more than reading it, but the hope is that 200 MB uncompressed is a more acceptable trade between fewer, larger files (easier on the bookkeeping) and more, smaller files (easier on the end user).
> Allows for plugin-specific chunks sizes

- docs/source/advanced/plugin_dev.rst
- strax/plugin.py
- tests/test_cut_plugin.py
The cuts currently in straxen (https://github.com/XENONnT/straxen/blob/master/straxen/plugins/x1t_cuts.py ) have a quite lot of overlap with one another. Most of the time a simple Boolean array is all that is returned. However, we each time have to add the time fields et cetera which may somewhat obscure the functionality.
To simplify the cuts somewhat I've written a simple Plugin Class. In straxen it could be used as for example:
```
class CutS1s(CutPlugin):
depends_on = ('events', 'corrected_areas')
provides = 'cs1_cut'
cut_description = "Remove cS1 above 100 PE"
cut_name ='cut_high_cs1'
__version__ = '0.0.0'
def cut_by(self, events):
return events['cs1'] > 100
```
```
class CutS2s(CutPlugin):
depends_on = ('events', 'corrected_areas')
cut_description = "Remove cS2s below 100 PE"
def …
```
> CutPlugin class for cuts in straxen

- docs/pull_request_template.md
When writing PRs in strax it might be good to add a template for both filing issues and adding PR. This can help keeping the pull requests in a similar format. It might also help authors to include things (like tests, documentation, examples) that would probably be requested by the reviewers.
> Create templates for strax

- strax/context.py
Apply a function in `get_array` just before returning the data.
This way, you can make a last-minute correction (or apply a blinding cut in the context).
When one loads data you do either `st.get_array` or `st.get_df` (which then calls `st.get_array` for you). In the lines changed in this PR, you see that the results that is usually returned directly can now be changed by a function. Such a function should be a function that takes a single argument (the data) and does something to it. For example in https://github.com/XENONnT/straxen/pull/166 it remaps some channels but this could also be used to apply a blinding cut.
**Can you give a minimal working example (or illustrate with a …
> Apply function to data

- strax/context.py
The issue is elaborated in https://github.com/AxFoundation/strax/issues/285
This PR is a small patch which will make the fuzzy_for option more flexible. The user can now specify any provides field in `fuzzy_for`. The user can now also just specify a string instead of a tuple.    
`st.set_context_config({'fuzzy_for': 'peaklets'})`
> Workaround for fuzzy_for issue.

- strax/plugin.py
If the first dependency of a loop plugin is produced by a multi-output plugin, the automatic determination of `loop_over` fails. During the automatic determination of loop order, `loop_over = self.deps[self.depends_on[0]].data_kind` ([plugin.py L610](https://github.com/AxFoundation/strax/blob/master/strax/plugin.py#L610)) evaluates to a dictionary rather than a string, and this fails 4 lines down when it dereferences `kwargs`.
This PR checks to see if the `data_kind` of the plugin providing the first dependency is a multi-output plugin and asks the user to be more specific if it is. Fixes #311 .
> Checks for multioutput plugins and loop dependencies

- .travis.yml
As illustrated in figure 4 of https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:dsg:daq:eb_speed_tests, python 3.8 showed an increased performance on the XENONnT eventbuilder machines. Therefore, we might want to test strax also for python 3.8.
> Add python3.8 to travis

- strax/chunk.py
- tests/test_hitlet.py
- tests/test_mailbox.py
Quick patch to an error we encountered in one of the latest runs. Although strange we shouldn't make this kind of errors cause the entire stack of the processing crash.
don't do x/0
**Edit after all the commits you can see in this PR**
Should have renamed this PR to 'fix travis issues'. This was the colateral damage:
- Apparently travis has started running with multiple threads. This means that we cannot rely on the old counting of threads.
- Secondly we ran into one of the conditional entropy tests. I slightly relaxed the math.isclose requirement.
> quick fix for zero division error - and Travis issues

- strax/processing/peak_building.py
- tests/test_peak_processing.py
The desaturation requires re-calculating the sum waveform of only a small fraction of the peaklets (that are saturated), once the (temporary copy of) records are corrected. It is best to be able to do partial re-calculation.
`func: sum_waveform` now takes a keyword argument `peak_list` of the type `numpy.array`. When not specified, default value would be converted into `np.arange(len(peaks))`
> Option to give range to sum_waveform

- strax/storage/mongo.py
Solves issue: https://github.com/AxFoundation/strax/issues/326
See:
https://stackoverflow.com/questions/28292542/how-to-check-if-a-number-is-a-np-float64-or-np-float32-or-np-float16
```python
d = np.float32(1)
isinstance(d, np.float), isinstance(d, np.floating)
(False, True)
```
> Do proper typetesting for np.floats

- strax/storage/mongo.py
We experienced that some documents got bigger than the 16 MB limit imposed by mongo due to many chunks being written to the same document. This is solved in this PR by splitting out the chunks-data and the meta-data into separate documents.
https://github.com/XENONnT/analysiscode/blob/master/StraxTests/add_mongo_saver_finetuning.ipynb
**Doc format**
See the gist below for an example. Here we uploaded three chunks with a length == 5 datafield (to keep it simple). This means we have four documents in total:
https://gist.github.com/jorana/c4fccefa1a152b403bace944a8993699
> Create seperate doc for new chunk

- strax/storage/mongo.py
Slightly tweak w.r.t. #335 (and #315). Only query the database for chunks once.
Use `find` to find all chunks, save it in ram and load it from there instead of doing up to 600 queries.
**Performance**
Using 
```python
%%timeit
om = st.get_array('009524', 'online_peak_monitor', allow_incomplete=True) # 161 chunks
```
_Before_
23 s ± 175 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
_After_
1.91 s ± 70.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> improve mongo-backend-loading

- strax/run_selection.py
Fix https://github.com/AxFoundation/strax/issues/331
We were updating the self.runs of the context but not returning it actually as the datasets that were selected in the st.select_runs
```python
st.select_runs(available=('raw_records', 'peaklets'))
```
this now returns the df that was asked for.
Previously did raise:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/strax/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
2894 …
```
> Fix strax.select_runs for available = tuple

- strax/corrections.py
Need to return sorted dataFrame by index when using function read()
here is an example of using read() and why is important to return sorted data to avoid confusions
https://github.com/ahiguera-mx/xenon/blob/master/plot_gains.ipynb
here is an example of using read() and why is important to return sorted data to avoid confusions
https://github.com/ahiguera-mx/xenon/blob/master/plot_gains.ipynb
Please make sure that all …
> Update corrections.py to return sorted dataFrame by read()

- strax/storage/common.py
This fixes https://github.com/AxFoundation/strax/issues/332
It allows you to print the StorageFrontend Class providing you with more usefull info.
```python
st = straxen.contexts.xenonnt_online()
for sf in st.storage:
print(sf)
``` 
returns
```python
straxen.rundb.RunDB, readonly: True
strax.storage.files.DataDirectory, readonly: True, path: /dali/lgrandi/xenonnt/raw, take_only: ('raw_records', 'raw_records_he', 'raw_records_aqmon', 'raw_records_nv', 'raw_records_aqmon_nv', 'raw_records_mv')
strax.storage.files.DataDirectory, readonly: True, path: /dali/lgrandi/xenonnt/processed
strax.storage.files.DataDirectory, …
```
> Add representation to strax.StorageFrontend

- strax/storage/mongo.py
Address #346 
Keep track of how many runs (datakinds) are stored in the buffer. If to large, dump some.
**MWE**
```python
for r in range(10165, 10165+10):
if st.is_stored(f'{r:06}', 'online_peak_monitor'):
st.get_array(f'{r:06}', 'online_peak_monitor')
print(st.storage[-1].backends[0]._buffered_backend_keys)
print(sys.getsizeof(st.storage[-1].backends[0].chunks_registry)/1e6)
```
> limit buffer for mongo backend

- strax/context.py
Here is the traceback, no need to say more:
```python
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-11-27129e865a03> in <module>
1 get_ipython().run_line_magic('matplotlib', 'notebook')
----> 2 OM.get_canvas(
3     st,
4     start_at_run= '10348', # This is the run I want to start from
5     store_fig_at = './201121_daq_test',  # some path you want to store each figure
/mnt/d/Google_Drive/PhD-master/ubuntu-storage/ubuntu-windows/software/analysiscode/OnlineMonitor/online_monitor/online_monitor.py in get_canvas(st, run_id, time_sleep, store_fig_at, start_at_run, lone_hits_style)
507         t_start = time.time()
508 
--> 509         om, _run_id = get_run_and_data(st, …
```
> Fix error progress_bar

- strax/context.py
Some frontends are harder to interface with than others. Using this new function, one is able to copy data from one frontend to another. This is especially useful in at least these two concrete examples:
1. Querying the database is in Mongo.py is expensive. Better save it to disk as that is quicker and prevents people from overloading the database.
2. The mongo backend is a nightmare to use outside of dali, it's much easier to transfer when backcasted to a normal DataDirectory frontend.
Strax magic! I wrote it such that it can be used either trying to write to all the other frontends or to a specific one (
```python …
```
> copy data from frontend to frontend

- strax/corrections.py
Change the way we init the pymongo client for the corrections. NB: the init is now done on the `straxen` side (makes more sense to do it in the nT specific package).
Given recent changes (https://github.com/XENONnT/straxen/pull/163), it makes more sense to use a centralized initiation for the pymongo client (i.e. `utilix`). 
All should work just as before. It's only when someone uses this script outside of the straxen environment that one should initialize a client (see https://github.com/XENONnT/straxen/pull/288).
> use utilix for client

- strax/plugin.py
- strax/storage/common.py
- strax/storage/mongo.py
- tests/test_loop_plugins.py
Allow loop-plugins to be used with multiple outputs.
I tried to write a new loop plugin, but this yielded quite an incomprehensible traceback that the dtype was wrong. We should at least make a better error. So I just modified the loop plugin to just work in this case. There is some copy pasting but given it's only 10 lines, I don't care too much.
The only downside is that, while solving this, I realized I don't actually need it.
Loop over assumed a single output, when a dict is returned for the different outputs, it got confused. Especially when setting up the results buffer.
> Allow loop_plugin for multi_output

- strax/plugin.py
- tests/test_core.py
- tests/test_loop_plugins.py
- tests/test_peak_properties.py
- tests/test_peak_splitting.py
Fix a slight mistake in https://github.com/AxFoundation/strax/pull/357 concerning the testing.
Further I've added some other tests while I was waiting on some computations to finish.
> Add more tests to strax

- tests/test_peak_splitting.py
Hotfix to fix issue https://github.com/AxFoundation/strax/issues/361. This PR solves two issues:
1. Makes the test reproducible
2. Disables check that is only working for local_minimum
This 2.nd issue was making some builds fail on travis. Did not catch that before.
> Fix reproducibility of peak split test

- strax/storage/files.py
**What is the problem / what does the code in this PR do & can you briefly describe how it works?**
You might have noticed that `st.select_runs` is getting slow lately. After some nice profiling, I traced back the issue to the operation I'm changing in this PR. For each run we could not find in the rundb (rucio) we used the [strax.DataDirectory](https://github.com/XENONnT/straxen/blob/master/straxen/contexts.py#L96) in the context. These in turn look for the keys not found yet. However, there is a very intensive check in `DataDirectory._find` that loops over all the files in the `DataDirectory` **for each of the missing keys!** This makes everything very very slow and without having to do so. This check makes sense only if one does a fuzzy search. Adding the requirement that this is …
> Speed up st.select_runs by factor ~100 with strict "_find" in files-storage

- strax/storage/mongo.py
The queries for the metadata always fetch the first rather than the last metadata doc in the collection. This fix is a **temporary** solution to fetch the last one. We will have to do a better job by adding the changes proposed in https://github.com/AxFoundation/strax/issues/365. This means, making the collection clean of any other documents that might be found by the query to this datakey as well as optimizing the syntax to not use slow operators.
Query the last document rather than the first.
> Temp fix query for md queries

- strax/plugin.py
Make a clear error message to notify the user. I also once or twice ran into this error so better to solve it.
See issue #238 for examples
> fix issue #238 for single key-word returns

- strax/plugin.py
See issue #372 for the problem.
When we create a `ParallelSourcePlugin`, there is some error in finding the `dtype` for a requested data type. This yields the error as in #372.
Usually this is not much of a problem but if we already have raw_records registered, this becomes a mess. I now just iterate over the known plugins to the `ParallelSourcePlugin` to find the right dtype. Given that we have been running like this for a long time illustrates that there are probably few people actually using strax to it's max performance and few will notice.
I'll upload a `multiprocess problem.ipynb` to the StraxTests on the …
> fix key error for non rr multiprocess

- strax/storage/mongo.py
As explained in https://github.com/AxFoundation/strax/issues/365 and https://github.com/AxFoundation/strax/issues/374 there are two things that need addressing:
- When re-making data, we should clear previous entries. -> To this end I added a `collection.delete_many` operation at the init of the saver. This should only happen when the data was not correctly stored. If it is already stored, you won't be accessing the `MongoSaver` anyways. This only happens when during progressing that there occurred an error, after this, there is an [exception](https://github.com/AxFoundation/strax/blob/a1c87937b9aa86105fdb0cff57590f3dbcfa72e6/strax/storage/common.py#L253) added to the metadata. We should delete this stuff if we try to process the …
> Better queries in online monitor

- strax/context.py
Adds keep_columns to iter/get_array doc strings. I am not sure if I am recalling it correclty, but I think we had this doc-string already before and lost it at some point. But, I wa snot able to track down the commit in which it happened.
> Added keep_columns into docstring

- strax/storage/mongo.py
Follow up on #375 and remove slow operators now that the TTL has flushed.
> remove slow operators from mongo storage

- .travis.yml
- requirements.txt
Address https://github.com/AxFoundation/strax/issues/229
Rather than figuring out e.g. numpy dependencies and compatibility in the requirements for strax, leave that to the base-environment (unless something is truly incompatible). Parse the requirements as set there (are tested against strax and straxen) such that we don't have to do it here. 
The way we set it up now is cyclically unlogical, causing failures like: https://github.com/XENONnT/base_environment/pull/444
This approach has been working perfectly for straxen:
https://github.com/XENONnT/straxen/commit/bde58e97fe2487a6abc5aa62879d344630a4a4e1
> Parse requirements for testing

- strax/context.py
Very very small tweak to progress bar. Was working on something related and recognized it might also work here, seems like it does. Could have written an issue but would have been as much work as this small tweak. Daniel did all the actual work 😉 .
Reduce the `get_iter` complexity by allowing a disabled progress bar.
**Extra feature**
Because we slightly changed how the pbar is set up, it now also works for `st.make` (at least, I thought this did not work before) :
> very small simplification of pbar

- strax/run_selection.py
Warn if targets are not saved. Otherwise people might get the wrong impression.
```python
st=straxen.contexts.xenonnt_online()
st.context_config['check_available'] = strax.to_str_tuple(list(st._plugin_class_registry.keys()))
st.select_runs()
```
```text
Peaks-plugin is SaveWhen.NEVER. Therefore peaks is most likely not stored!
EventInfoDouble-plugin is SaveWhen.NEVER. Therefore event_info_double is most likely not stored!
nVETOPulseProcessing-plugin is SaveWhen.TARGET. Therefore records_nv is most likely not stored!
PeakPositionsNT-plugin is SaveWhen.NEVER. Therefore peak_positions is most likely not stored!
nVETORecorder-plugin is SaveWhen.TARGET. Therefore …
```
> Warn for non saved plugins, fix #379

- strax/run_selection.py
See #388 (thanks for the detailed report @Jianyu010.)
When providing the available argument, we are not actually adding that to the things to check. This is an easy fix.
> Fix #388 select runs with user defined available

- strax/mailbox.py
- strax/plugin.py
- strax/testutils.py
This is a fix for exception handling during multiprocessing. Previously, if strax crashed during multiprocessing, `_temp` directories could remain on disk, and exceptions were not always recorded in metadata. This should fix that. It's a low-priority PR: this won't prevent any crashes, just handle them slightly nicer. In other words, a perfect hobby project for a 'retired' colleague ;-).
The problem in more detail: 
* If an exception occurs, exceptions propagate through strax's mailbox system. Usually, all savers subscribe to some mailbox, so they will receive the exception, write it in their metadata, and close gracefully. (https://github.com/AxFoundation/strax/blob/master/strax/storage/common.py#L577)
* During multiprocessing, …
> Close inlined savers on exceptions in multiprocessing

- strax/context.py
Very small patch to prevent messages like:
```python
Loading ('_tempnhdc',): ...
```
> don't print for temp plugins

- strax/dtypes.py
- strax/processing/pulse_processing.py
- tests/test_general_processing.py
Add a function to more easily numbafy the copy from dtype to dtype. Also see https://github.com/XENONnT/straxen/issues/353
Numba magic 🧙 
Rather than writing each time a cumbersome function that has to get the dtype write, why not code this. The annoying thing about numba is that it does not allow you to use strings to loop over. This is a workaround.
```python
r = np.ones(1000, dtype=strax.raw_record_dtype()
def test_raw_to_records(r):
buffer = np.zeros(len(r), r.dtype)
strax.copy_to_buffer(r, buffer, "_test_r_to_buffer")
if len(r):
assert np.all(buffer == r)
```
**Special thanks to**
Daniel for helping writing …
> allow dynamic function creation for dtype copy

- strax/context.py
- strax/storage/common.py
- strax/storage/files.py
- strax/storage/mongo.py
Allow the timeout for the saver to be specified at the context level.
When storing files [with high compression](https://github.com/XENONnT/straxen/pull/358), one might change the context to allow also slower savers. However at the moment this is not such a trivial task. Using the context_config, we can change this number to some different value without having to change the strax source.
> specify saver timeout at context level

- strax/context.py
Fix issue #398 for progress bars that appear to be unfinished.
There can be some jitter at the end of a run that appears to say you are are 99.x % or 100.x % whereas you are simply done, and we should set to progress to exactly 100%.
> clip progress progressbar

- strax/context.py
We determine the start/stop of a run from the metadata. If that fails, we try getting it from the target currently requested. However, if we are making that target, this of course doesn't work. Therefore, it makes a lot more sense to check all the datatypes if they are stored and determine the start and stop based on the datatype-metadata.
This is helpful e.g. when raw-records is stored but we want to make peaks. (And don't have access to the runs-metadata).
> Infer start/stop from any dtype

- strax/context.py
I often want a broad overview of the different data types, their lineage hashes, and whether they are saved to disk or not. This is especially useful for e.g. reprocessing or for comparing the changes to hashes between different contexts.
It's a convenience function -- no new functionality. I thought making it a `property` would be best to make it immutable (or at least more difficult to mutate) but still a dictionary which is nice to work with.
Sure:
```
import strax
from pprint import pprint
import numpy as np
_dtype_name = 'variable'
_dtype = ('variable 1', _dtype_name)
test_dtype = [(_dtype, np.float64)] + …
```
> Add property provided_dtypes to Context

- strax/processing/general.py
- tests/test_general_processing.py
In this PR we numbafy `split_by_containment` and change its return value into a numba.typed.List instead of a normal Python list. This has the advantage that the result of `split_by_containment` can be used in numba njitted functions which enhances there speed. Further, this PR increases the performance of  `split_by_containment` by a factor of x2 to x4 depending on its inputs. This performance increase will directly manifest in a performance increase of LoopPlugins. 
If the numba.typed.List output is used instead of a LoopPlugin one can gain another factor x10 boost if needed. This enables maybe new usages of `split_by_containment`. 
In addition to the function changes I added small tests to ensure, that the required replacement …
> Numbafy split by containment

- strax/context.py
- tests/test_core.py
On the eventbuilders we need to compute targets that are not always depending on one another. For example [event info](https://straxen.readthedocs.io/en/latest/reference/datastructure.html#event-info) and [online_peak_monitor](https://straxen.readthedocs.io/en/latest/reference/datastructure.html#online-peak-monitor) don't depend on each other and don't have the same datakind. This makes it impossible to use `st.make` on these target.
So far, I've been using a [https://github.com/XENONnT/straxen/blob/master/bin/bootstrax#L327-L335](work-around) of registering a temporary plugin for merging these non-unify-able targets. However, this is causing quite some issues in the merging step especially given the fact that the online-peak monitor is a monolithic event per chunk (i.e. unable to split …
> Allow multiple targets to be computed simultaneously

- strax/context.py
- tests/test_core.py
Tweak to #408 after [feedback from Jelle](https://github.com/AxFoundation/strax/pull/408#issuecomment-797667287).
Three small tweaks:
1. Don't allow lazy mode for `allow_multiple`
2. Don't allow `timeouts >7200` for `allow_multiple`. Set this as a hard coded value for the moment.
3. Make sure to abide the order of the targets as specified in `get_iter`. We for now should be a little smart about the order of the plugins in order not to fall into the mailbox timeout. (Failures happening outside the final-target subscribers will only get caught by the last resort timeout of the mailboxes).
> Tweaks to multitargets

- strax/run_selection.py
- tests/test_core.py
Imagine, you want to have a detailed report for a single run what is stored and what is not. This is chunky with current strax. Therefore, this PR adds a function that allows you to check what is stored for a single run with some simple regex matching.
```python
st.available_for_run('012275', 
include_targets = ('raw_records', 'peaklets'))
```
target | is_stored
-- | --
peaklets | True
raw_records | False
```python
st.available_for_run('012275', 
include_targets = ('*record*'),
exclude_targets = ('*_mv', '*_nv', '*_he'))
```
target | is_stored
-- | --
records | False
raw_records | False
raw_records_aqmon | False
```python
st.available_for_run('012275', …
```
> Check data availability for single run

- strax/context.py
- tests/test_context.py
Move the `apply_data_function` logic from `st.get_array` to `st.get_iter` to avoid any malicious/accidental usage of `st.get_iter` thereby bypassing `apply_data_function`.
Additionally, we fix an issue we had for a while in straxen that this option was incompatible with selection strings:
https://github.com/XENONnT/straxen/blob/5c945e141bee0d5fa976a6e1a78516a0a172305a/straxen/common.py#L491-L493
Therefore, move the application of this function prior to the application of a selection string.
apply_data_function is applied just prior to returning the data to the user.
See the tests as simple examples of use cases.
> update apply function to data & test

- strax/context.py
- strax/utils.py
- tests/test_utils.py
`context.apply_selection` is a very useful function that could be exploited elsewhere too like in (straxens online monitor)[https://github.com/XENONnT/straxen/blob/master/straxen/plugins/online_monitor.py#L324]. We can easily take it out of the context and put it in the `strax.utils` such that we can more easily use this logic.
I have for now made the function still callable in the context but with a deprecation warning.
> Move apply selection from context to utils

- strax/processing/peak_building.py
- tests/test_peak_processing.py
- tests/test_utils.py
Add a test that will push us into #397.
Make a big bunch of records that should be sufficient to break strax with integer overflows. To solve the issue, we should solve this test.
This is the example
> add failing dt test - and solve it with max peak duration

- .travis.yml
> Allow Py39 in travis tests

- strax/dtypes.py
- strax/processing/hitlets.py
- strax/processing/peak_splitting.py
- tests/test_hitlet.py
- tests/test_peak_splitting.py
In this PR Tianyu and I (mostly Tianyu) refactored the get_hitlet_data function. Tianyus proposal makes the function much more flexible as we search no longer for the hitlet data via the `record_i` field but using time intervals instead. This change allows a much more general usage of the function. For this reason I added a "header" part which checks for different possibilities in calling this function. The corresponding tests have been added too.
Beside get_hitlet_data I refactored a bit concat_overlaping_hits as it was also part of the proposal. However, I did not manage to modify the function such, that it mimics the full behavior of the old method. But since the new method would lead to a performance drop of about 30% I …
> Refactor concat and get data

- strax/dtypes.py
- strax/processing/hitlets.py
- strax/processing/peak_splitting.py
- tests/test_hitlet.py
With this PR we refactor the hitlet data_type a bit. 
1. get_hitlet_data also supports now empty inputs. A corresponding test was added.
2. The the hitlet dtype with data field was extended by goodness of split and max gap. This allows to share the _split_peaks function of our PeakSplitter class. Hence we can remove some redundant code. 
3. I refactored straxen's hitlet plugin by adding a new function called `create_hitlets_from_hits`. This gives the plugin a bit more structure and generalizes hitlets such that it can also be used more easily for other analyses. Further, this allowed to remove the `refresh_hit_to_hitlets`.
This PR goes together with [#463](https://github.com/XENONnT/straxen/pull/463/files).
> Refactor hitlets

- strax/processing/hitlets.py
We are seeing some runs (020330) where nveto is failing because of division by zero errors caused here.
We need to figure out where this happens, but that needs some deeper investigation.
> Temporary patch div/zero in hitlets

- strax/run_selection.py
@WenzDaniel just noticed this, let's not remove the underscore from the tag if the pattern also has an underscore.
> Don't ignore if pattern also startswith underscore

- strax/plugin.py
In the overlap window plugin, we are strict for the end-time of the cached chunks. However, we are not so strict about our start times in the cached_input. This PR addresses this.
Since we use `v.split(t=prev_split, allow_early_split=True)`, we can get chunks split on different times (the allow_early_split is True). This causes issues when one from chunk>0 tries to add the cached input into the `super().do_compute`. We don't want to `allow_early_split=False` since that raises an error to deal with. Instead, we can use the split point (i.e. start time) from the other chunk(s) to split on since allow_early_split=True. This will only increase the bit of information that is being send to the …
> Match cached buffer chunk start times OverlapWindowPlugin

- strax/context.py
- strax/processor.py
Due to a few subtle interacting bugs / missing checks, a situation can occur where a new mailbox gets created __after__ processing has started. If this happens during https://github.com/AxFoundation/strax/blob/master/strax/processor.py#L216 we get the crash Peter reported in https://github.com/AxFoundation/strax/pull/444. But in principle this could happen at any later time, in which case messages would probably accumulate in the unattended mailbox until we run out of memory. For more details, see https://github.com/AxFoundation/strax/pull/444. 
This will:
* Replace the `MailboxDict` with a regular dict at the end of `ThreadedMailboxProcessor.__init__`, stopping automatic mailbox creation …
> Prevent late creation of unattended mailboxes

- strax/processor.py
_this PR was edited after Yossi's review and uses his proposal instead_
In PR #452 we have set the behavior of the mailbox dict to be non-defaultdict like. This however causes problems when only ParallelSourcePlugin plugins are subscribed since the results from these plugins are saved under the divide_output mailbox. 
As per @jmosbacher 's suggestion https://github.com/AxFoundation/strax/pull/463#issuecomment-857522815, the correct way of dealing with it is making sure there is a mailbox for each of the outputs of a multi-output plugin.
**The error:**
https://github.com/AxFoundation/strax/pull/452#issuecomment-855790815
> Fix #452 assert there is a mailbox for the final generator

- strax/plugin.py
Simple PR, the name says already all. Cut plugins can take a few minutes to compute. Hence, we should allow users to store the cuts instead of recomputing them every time they start an analysis.
> CutPlugins save when plugin is target

- strax/processing/peak_building.py
Fix a bug that's causing pulse saturation check not working. The right condition should be `max_in_record >= int(baseline)`, as `record = int(baseline) -  raw_record` and pulse saturation results into `raw_record = 0`
> Fix digitizer saturation check

- strax/processing/peak_properties.py
After reconstructing peaklets with saturation correction, we need to update the widths for selected peaklets. For this purpose, I propose to add a `select_peaks_indicies` key to the compute width function.
I couldn't find a way to do this without changing this function in strax because numpy structured array assignment is a bit tricky i.e.
`arr[index]['x'] = new_values` will not update the values
`arr['x'][index] = new_values` will update the values
> Add select index to compute width

- strax/plugin.py
Trivial change, I just re-aranged the time field position in our CutPlugin.  In an array of merged plugins the result will look like
```
False, 1621861432156179212, 1621861432159096710,  True, False,  True,  True, False
```
which drove me crazy.
> Re ordered time field in cut plugins

- strax/context.py
- strax/utils.py
As discussed in https://github.com/AxFoundation/strax/pull/476, change the default behavior for loading multiple runs since having two competing pbars is messy.
Also make the runs-pbar configurable.
Rather than disabling the pbar altogether (as in  #476) only do it for multiple runs in the multi-run code.
> change default pbar behavior (for multiple runs)

- strax/utils.py
Changes default dtype for offset in growing result to np.int64 removes the following warning from tests:
```
../strax/strax/utils.py:60
/home/dwenz/mymodules/strax/strax/utils.py:60: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
def growing_result(dtype=np.int, chunk_size=10000):
```
> Change growing result offset dtype to int64

- strax/context.py
- strax/utils.py
- Massive speedup for loading many runs
- When `use_per_run_defaults == False` we don't allow for changing lineages in the context. If so, there is no need to for every run recompute the lineage of each plugin
- This is a similar PR to https://github.com/AxFoundation/strax/pull/440.
**This only works when we have fixed lineages**, but when they are fixed, we don't need a full initialization of the plugin when we are going to load a new run. We can just re-use a plugin and only change run run_id attribute. To this end:
- Initialize the plugin once
- Cache the plugin in the _fixed_plugin_cache. To prevent a changed config not being reflected in the plugin (e.g. you load data and later change an option), we make a sha1 of the `st.config` any changes there will result in a new hash, and as …
> Fix lineage if per run default is not allowed

- strax/context.py
- strax/plugin.py
- tests/test_fixed_plugin_cache.py
- tests/test_loop_plugins.py
So although #483 seemed nice, @jmosbacher  correctly pointed out that for multi-threading multiple runs, this can cause issues. In fact with the `.deps` tracking in the plugins, we were ever more obscurely shipping configs from older runs into the processing.
I should have written a test for it to catch these issues. So that is added in this PR.
For the copy function several things could be copied that are setup during the init of a plugin:
- `Plugin.deps` (the dependencies of the plugin that point to lower-level plugins)
- `Plugin.infer_dtype()` results
- `Plugin.setup()` results
- `Plugin.config` (set in `Context._set_plugin_config`
- `Plugin.lineage`
In the current implementation we went for reliability over performance. This means we only copy the `Plugin.config` and `plugin.lineage`. …
> Copy plugin instance for processing

- strax/chunk.py
- strax/context.py
- strax/io.py
- strax/mailbox.py
- strax/plugin.py
- strax/processing/data_reduction.py
- strax/processing/hitlets.py
- strax/processing/peak_building.py
- strax/processing/pulse_processing.py
- strax/run_selection.py
- strax/storage/files.py
- strax/storage/mongo.py
- strax/storage/rucio.py
- strax/storage/zipfiles.py
- strax/testutils.py
- strax/utils.py
- tests/test_loop_plugins.py
- tests/test_mailbox.py
- tests/test_pulse_processing.py
- tests/test_utils.py
I'm getting very annoyed by codefactor lately, it's complaining about all kinds of places one has not even touched. Let's start with giving it less gunpowder and work from there.
Remove todos and disable checks where they are just wrong.
> Reduce codefactor

- pytest.ini
Tiny PR which adds a ini for pytest which sets `numba.NumbaExperimentalFeatureWarning` to ignore. Reduce the amount of lengthy warning messages during testing.
> Added pytest.ini

- strax/context.py
- tests/test_saving.py
- Use self.key_for in get_components instead of strax.DataKey
- add a small test. I thought something did not work well but actually, it does.
> Simplify get_components

- strax/context.py
- tests/test_superruns.py
Changed get_components such that superruns can be created from every plugin type except SaveWhen.NEVER plugins. This addresses: https://github.com/XENONnT/straxen/issues/605
> Allow creation and storing of superruns if SaveWhen > 0

- strax/run_selection.py
- strax/utils.py
Two small patches to the pbar
Fix:
- ![afbeelding](https://user-images.githubusercontent.com/22295914/135720583-ba6a3107-386f-4615-8b56-c93e2ce7cddc.png)
and make this a notebook pbar:
- ![afbeelding](https://user-images.githubusercontent.com/22295914/135720588-664da400-6d91-447f-add3-8b5ff6488257.png)
> Two pbar patches

- extra_requirements/requirements-tests.txt
- strax/context.py
- strax/utils.py
- tests/test_utils.py
In this PR we rework the job submission in multi-runs to address:  https://github.com/AxFoundation/strax/issues/563. The new function will always just submit twice as many jobs as there are workers. As soon as a job finishes its job the result is loaded and new jobs are submitted if needed. In this way we ensure that garbage collection is called in time on each individual worker. 
In addition I changed the function such that the output is sorted by run_id which was previously not the case. In terms of performance no significant increase in computing time can be observed. 
To test the different behavior just call 
```
st.make(run_ids, data_type)
```
or 
```
st.get_array(run_ids, data_type)
```
for more than a single run_id and …
> Fix memory explosion multi runs

- strax/context.py
Decrease the amount of user-warnings. Especially during simulation, these can be quite annoying.
Setting the following is sometimes simply more convenient:
```python
st.log,setLevel(logging.ERROR)
```
> use logged warnings

- strax/storage/files.py
- strax/storage/mongo.py
- tests/test_storage.py
For WFSim, sometimes users use a run-naming scheme which relies on `'-'`, for example `'run-0'`. This sounds quite intuative and there is also nothing clearly wrong with choosing such a name. However, this leads to very strange results with some of the Strorage frontends, which do not understand folders with too many `'-'`s. 
So let's fail when a user tries using a run_id with `-`. I think we can easily live without this flexibility.
> fail for - run_ids

- strax/context.py
- tests/test_config.py
- tests/test_context.py
Sometimes you want to process `event_info` but don't know if you have all the required datatypes that are needed for making that data. Rather than doing a try for except, you might from the start want to know if that data can be computed, and where you need to start processing from.
In this PR we add just that.
Look at the target you want to compute, if it's not stored, check if the dependencies are stored. If finally you reach a plugin that is either not stored or not depending on anything (`raw_records`), return `None`, indicating that you cannot make this data.
> Add funcs for getting stored source

- strax/processing/hitlets.py
- strax/processing/statistics.py
- tests/test_statistics.py
Small PR which fixes the definition of the highest density region.  The difference is illustrated in the image below:
In the previous version we computed the area wrongly in case one is truly  interested in the HDR.  So far this function was only used to get a width estimate for the hitlet data_type. No need in straxen needed. The behavior of the already existing function was changed such that they behave consistently. 
I also added a test which shows that the HDR of the 68.27% a normal distribution corresponds to the expected +/- sigma.
> Make truly HDR

- .github/workflows/pytest.yml
- We could increase coverage by running straxen tests on coveralls
- We could check if changes in a PR would cause issues for running straxen. A fail here would mean we introduce breaking changes. We could either avoid doing that or allow it and fix it on straxens master 
In this PR, we don't use any of straxens secrets, so we don't have database access
> test straxen for coverage and backward compatibility

- .github/workflows/pytest.yml
- strax/context.py
- strax/plugin.py
- strax/run_selection.py
- strax/testutils.py
- tests/test_context.py
Fix some issues introduced in features added in https://github.com/AxFoundation/strax/pull/631
also see https://github.com/XENONnT/straxen/pull/879
> Fix savewhen issues

- tests/test_saving.py
- tests/test_storage.py
Change the tempdir creation of some of our tests. The new procedure uses a tempdir created by `tempfile.TemporaryDirectory` this method has a weak  reference in its init which ensures that the directory gets deleted if its reference is garbage collected. In this way we can ensure permission denied erros etc. on shared systems like dali. 
See also: 
https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory
and
https://stackoverflow.com/questions/50649701/shutil-rmtree-does-not-work-on-tempfile-temporarydirectory
> Change tempdirs in test

- strax/context.py
- tests/test_multi_output.py
Fixes a bug in our save_when extension introduced in https://github.com/AxFoundation/strax/pull/631. I forgot to check whether "lose-end" data_types like `pulse_counts` are stored properly after inlining plugins. The issue arises from the fact that we return early in [this line of get_components](https://github.com/AxFoundation/strax/blob/ef37118b1c3302b0af49179bd46629f619b3f98a/strax/context.py#L928) for records.
> Add tests for lose ends

- strax/context.py
- strax/run_selection.py
I apologize for this pedantic PR in advance, but this page just looks horribly formatted:
https://straxen.readthedocs.io/en/latest/reference/context.html#strax.context.Context.event_display_interactive
Fix indents etc
In case you see another place where there should be a fix, feel free to edit this PR
Should be better after this PR:
https://strax--684.org.readthedocs.build/en/684/reference/strax.html#module-strax.context
> Docs fixing

- strax/context.py
- tests/test_context.py
Allow different chunk target size from original
> Allow different chunk size

- strax/plugin.py
- tests/test_context.py
Add auto-inferring option to plugin by setting `__version__ = None`. Fixes #217
Generate a hash on the fly by hashing the plugin class.
Please see the appended test for a use case.
**Catches and pitfalls**
With https://github.com/AxFoundation/strax/issues/688 around, this would lead to some ambiguous results in the affected methods.
> Auto version, fix #217

- strax/processing/peak_building.py
Despite that [straxen does take this into account](https://github.com/XENONnT/straxen/blob/master/straxen/plugins/peaklet_processing.py#L259-L262), I think we should add a clear comment as this might not be intuative
> Add n_hits comment in code

- strax/processing/hitlets.py
The default method for create hitlets from hits returns bad results. Comparing ints and floats in numba is not recommendable, I suspect that the compare [between them did not work well on this line](https://github.com/AxFoundation/strax/blob/6aa0a4d0d33f73650139e2a2ebc162d0f0e27c89/strax/processing/hitlets.py#L107).
So now, lets just take the largest and smallest numbers in `np.int64`
See the issue here:
And the difference between ints and floats (the default was np.inf) for the `chunk_end`
> Prevent float/int funkyness in hitlet processing

- strax/storage/mongo.py
- tests/test_mongo_frontend.py
In https://github.com/AxFoundation/strax/issues/346, we uttered the prophetic words
```It's just the backend-buffer that is sitting otherwise idle in the background eating your RAM that needs clearing.```
We now learned that this is true when we have longer than usual runs and data with large volumes.
We also should have known that the `sys.getsizeof` wasn't taking the total size of the document but only of the dictionary.
This PR fixes both with using numpy for the buffers such that the max size of buffers is respected by the backend.
> Numpy caching of data in online monitor storage

- strax/processing/peak_merging.py
- tests/test_peak_merging.py
The (lone hits) delta peaks added to `merged_s2s` waveforms have wrong time stamp. For example, in the example `merged_s2s` waveforms below, the red shadow marks peaklets while the blue shadow marks where we expect the lone hits, given the time stamps directly from `lone_hits` datatype. You can see the lone hits show up in the wrong time.
This PR did a minimal fix to this issue.
```
index = (p['time'] - lh_i['time'])//p['dt']
```
is the problem. Apparently, lone hits' time should show up only after `merged_s2s` start. This implementation means that `index` is always negative, leading to a reversed ordering thus mirrored relative timestamp.
**Can you give a minimal working example (or …
> fixed delta peak timestamp problem

- bin/rechunker
- strax/__init__.py
- strax/storage/file_rechunker.py
- strax/storage/files.py
- tests/test_storage.py
Rechunking of our data is much sought after by computing as our framework creates many small files that make them cumbersome to handle. Therefore we added a tool which does this in https://github.com/AxFoundation/strax/pull/686. We are now expanding it's use cases by implementing it in the DAQ workflow in https://github.com/XENONnT/straxen/pull/1074.
For https://github.com/XENONnT/straxen/pull/1074 I noticed the rather poor performance if all files are rechunked in serial. Therefore, I looked into parallelizing the load->saver + rechunk approach. I re-used the mailbox paradigm for this - as it was easier than just making some home-grown algorithm. Doing some parallelization here makes sense for it is similarly dependent on I/O as …
> Rechunker using Mailbox

- strax/storage/file_rechunker.py
Very small patch to #710 to report the right compressor
> Patch md access in the rechunker

- strax/processing/general.py
`'channel'` was changed in https://github.com/AxFoundation/strax/blob/b0e7fdcd21d2f4b5c141b528b448dd0bd4b7583a/strax/processing/general.py#L21-L24. 
So use `x['channel'].copy()` to make a copy of `x['channel']` to avoid this bug. 
> Do not change channel when sort_by_time

- strax/processing/general.py
- strax/processing/statistics.py
- strax/run_selection.py
- strax/utils.py
As the title described. 
This PR is trying to prevent issues like https://github.com/XENONnT/straxen/issues/1175. 
Similar to https://github.com/XENONnT/straxen/pull/1176. 
> Fix argsort inside numba.jit using kind='mergesort'

- strax/run_selection.py
Select_runs is too slow since we check frontend availability for all runs in the run_db and then apply the tag mask. By moving the checking after the tag selection, we can accelerate run selection by 20 times for the runs we are interested.
> Accelerate select_runs

- strax/processing/general.py
In some insane cases, where both `endtime` of `things` and `container` are not sorted, like:
```
things = np.array([(0, 1, 1, 0),
(1, 5, 1, 0),
(2, 1, 1, 0)],
dtype=strax.interval_dtype)
containers = np.array([(0, 4, 1, 0), (0, 1, 1, 0)],
dtype=strax.interval_dtype)
```
The current algorithm will give wrong results:
```
[[0, 3], [0, 3]]
```
The correct answer is:
```
[[0, 3], [0, 1]]
```
The new algorithm only search for interval when the `time` and `endtime` of `things` and `containers` are sorted. If not, we first sort them and record the `argsort`, then later recover the order following `argsort` of input. 
When `things`' `endtime` are not sorted, we will return the indices of the …
> Fix touching window

- strax/processing/general.py
- tests/test_general_processing.py
Sometimes `things` in `abs_time_to_prev_next_interval` might be overlapping, or the `endtime` might be not sorted. So throw warning instead of error, following the logic of `touching_windows`. 
Just change the warning logic, the algorithm is not changed. 
> Use warning also in `abs_time_to_prev_next_interval`

- strax/context.py
- strax/utils.py
- tests/test_utils.py
In this PR we extend the selection_str feature to allow to pass arbitrary small or more complex functions for the data selection, e.g., one could pass a function like:
```python
def s2_width_cut(events):
....
st.get_array(run, 'event_info', selection=s2_width_cut)
``` 
The selection function must take only a single argument which represents the data array itself. For example functions which take additional parameters must be reduced first:
```python
def s2_width_cut(events, para1, para2):
....
st.get_array(run, 'event_info', selection=lambda x: s2_width_cut(x, para1=1, para2=2))
```
> Add small selection functions

- strax/context.py
- strax/testutils.py
- tests/test_context.py
Adds fix and test for https://github.com/AxFoundation/strax/issues/747
> Patch plugin cache

- strax/context.py
- strax/utils.py
Split `compare_metadata` into `utils.compare_dict`, to use `utils.compare_dict` somewhere else.
> Split compare_metadata into utils.compare_meta

- strax/processing/general.py
`strax._check_objects_non_negative_length` checks to see if there are any data entries such that endtime-time >=0. However, when there is an error in the endtime such that endtime is very negative, endtime - time sees an overflow error, and native python would have endtime - time >0. Such an example can be seen in pema (see PR: [#333](https://github.com/XENONnT/pema/pull/333)) As such, native python would not detect such cases using _check_objects_non_negative_length. In actuality, it seems that numba has a check which somehow bypasses this overflow error, and detects such cases anyway but this is an instance of unexpected behavior.
Simply change the statement …
> Change endtime - time >= 0 to endtime >= time

- strax/storage/common.py
- strax/storage/files.py
- strax/storage/mongo.py
- strax/storage/zipfiles.py
To ease the workflow of developing a new `StorageBackend`, the PR mandatorily wraps `_read_chunk` in a `check_chunk_n` decorator instead.
> Mandatorily wrap `_read_chunk` in a `check_chunk_n` decorator

- strax/context.py
- tests/test_context.py
Bad things happen if plugin A registers to make X and Y, then B registers to make just X.
For example, strax's will first say B is producing X, as it should. Then you ask who is producing Y, it will say A. But now ask again who is producing X -- strax changes its mind and says A is producing X!
This happens because these 'partial registrations' break the assumptions of the plugin caching system. But that won't be all: if we actually tried to make Y the Processor shouldn't be smart enough to make two X's and throw away the bad one. Even if it was, would a user asking for X and Y really expect them to come from two different plugins?
This PR ensures a plugin is completely deregistered once …
> Deregister partially replaced multi-output plugins

- strax/processing/general.py
Avoid a `NumbaDeprecationWarning` and a future crash from using the deprecated function `numba.generated_jit`.
`numba.generated_jit` is deprecated: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit. I think most people don't see the warning message for this yet because our environments use numba versions that are more than a year old.
We use `generated_jit` in `strax.endtime` to condition its behavior on the dtype of its input. This PR replaces `generated_jit` with `numba.extending.overload`. An additional benefit is that we don't need to condition on the environment variable `NUMBA_DISABLE_JIT` anymore, this was one of the main reasons …
> Avoid deprecated generated_jit

- strax/context.py
- strax/plugins/plugin.py
In this follow up PR for https://github.com/AxFoundation/strax/pull/768 we change a bit the plugin caching. The plugin caching was introduced in https://github.com/AxFoundation/strax/pull/483 followed by two fixes in https://github.com/AxFoundation/strax/pull/485 and https://github.com/AxFoundation/strax/pull/545. In https://github.com/AxFoundation/strax/pull/483 it was decided to sacrifice a bit performance over reliability, and thus do not cache for example the `plugin.deps` which also required to rerun `fix_dtype` when loading plugins from cache.
In this PR we add `deps` to the cached plugins and remove the `deps` computation and `_fix_dependency` which calls `fix_dtype` from `__get_requested_plugins_from_cache`.  The change …
> Also copy dps and remove redundant checks.

- strax/utils.py
- tests/test_utils.py
> Using the aliases of builtin types like np.int is deprecated
reference: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
In principle the auto tests in https://github.com/XENONnT/base_environment/pull/1483 will not pass, but the line changed in this PR was never checked:
> `np.float` is deprecated

- requirements.txt
- tests/test_superruns.py
> Update pymongo and solve the error of pytest

- HISTORY.md
- strax/dtypes.py
- strax/plugins/down_chunking_plugin.py
- strax/plugins/plugin.py
- strax/processing/hitlets.py
- strax/processing/peak_splitting.py
- strax/run_selection.py
- strax/testutils.py
Remove `DownChunkingPlugin.iter` because it is just inheriting the `super().iter`.
> Remove a redundant function and fix some style

- strax/context.py
- tests/test_context.py
Update `_get_source_sf` to `get_source_sf` to return a list of frontends that store the target(s).
> Find the frontends which stored the targets

- strax/chunk.py
- strax/storage/common.py
- tests/test_storage.py
This fixes a crash @cfuselli always sees after restrax for some time.
In #758 we made StorageBackend check that the chunk length matches the length specified in the metadata. We wrap the class attribute _read_chunk in `__new__`. But `__new__` runs every time we make a new instance. Applications that make backends many times (like a running restrax session) end up with many layers of wrappings, and eventually hit python's recursion limit.
This keeps the check (and its unit test) but implements it more simply. Since `_read_chunk` is only used in `StorageBackend._read_and_format_chunk`, we can just add the check there. It will still apply to every storage backend.
@dachengx please let me …
> Simpler chunk length check, avoid recursion limit crash

- extra_requirements/requirements-tests.txt
Use `base_environment` for pytest, following https://github.com/XENONnT/base_environment/pull/1487.
> Deprecate the usage of `XENONnT/ax_env`

- strax/io.py
- tests/test_storage.py
Using only information inside the folder
Sometimes we want to directly load the strax file in a folder, without initializing plugins or context.
```
results = strax.dry_load_files(dirname)
```
this will load all files inside a folder.
```
results = strax.dry_load_files(dirname, 1)
```
this will load the 2nd chunk inside a folder.
Please make sure that all automated tests have passed before asking for a review (you can …
> Add a function to directly load file from strax folder

- strax/context.py
To solve https://github.com/AxFoundation/strax/pull/816
> Increase the timing precision of progress bar

- strax/context.py
Bug observed if:
```
import strax
st = strax.Context()
class A(strax.Plugin):
@property
def depends_on(self):
self._depends_on = tuple()
return self._depends_on
@depends_on.setter
def depends_on(self, str_or_tuple):
self._depends_on = strax.to_str_tuple(str_or_tuple)
st.register((A,))
st.deregister_plugins_with_missing_dependencies()
```
error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 17
13         self._depends_on = strax.to_str_tuple(str_or_tuple)
15 st.register((A,))
---> 17 st.deregister_plugins_with_missing_dependencies()
File ~/strax/strax/context.py:416, in …
```
> Initialize plugin because `depends_on` can be property

- strax/io.py
In `strax/storage/common.py`, the number of items in metadata and data is checked: https://github.com/AxFoundation/strax/blob/208d5309a3eb706a90d8cf7e6eee266bad121adc/strax/storage/common.py#L532-L536
This PR also checks this in `dry_load_files` function
> Check the consistency of number of items in metadata and data in `dry_load_files` function

- strax/plugin.py
Previously, `strax.plugin.CutPlugin` or `from strax.plugin import CutPlugin` will cause error:
```
>>> strax.plugin.CutPlugin
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'strax.plugins.plugin' has no attribute 'CutPlugin'
>>> from strax.plugin import CutPlugin
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/xudc/strax/strax/plugin.py", line 2, in <module>
from plugins import (
ModuleNotFoundError: No module named 'plugins'
```
This means that `strax/plugin.py` is never properly used., so we delete them.
Please include the following …
> Remove `strax.plugin`

- strax/context.py
- strax/plugins/overlap_window_plugin.py
- strax/processor.py
- strax/utils.py
- tests/test_mailbox.py
- tests/test_peak_processing.py
- tests/test_superruns.py
Pick out the lines inside `strax.utils.apply_selection` where the `selection` is applied to be a stand-alone function `parse_selection` for other uses. Nothing changed functionally.
> Pick out selection applying function

- strax/chunk.py
Negative `start` is not compatible with https://github.com/AxFoundation/strax/blob/9454279b1f25c5992fe7103f8a63080aa3047869/strax/plugins/overlap_window_plugin.py#L25 and https://github.com/AxFoundation/strax/blob/9454279b1f25c5992fe7103f8a63080aa3047869/strax/chunk.py#L270
> Prevent start being negative

- strax/context.py
Previously only the first base class is recorded, but the change of second or third base classes are not recorded in the lineage. So the change of second or third base classes will not be reflected in lineage so might cause trouble in processing and loading data.
> Record all base classes when multiple inheritance

- strax/plugins/down_chunking_plugin.py
- strax/plugins/plugin.py
- strax/testutils.py
- tests/test_down_chunk_plugin.py
To solve the comment https://github.com/AxFoundation/strax/pull/769/files#r1386797972.
Now we require `strax.DownChunkingPlugin.compute` to output generator of `strax.Chunk` for single output plugin, and generator of dictionary of `strax.Chunk` for multiple output plugin.
> Multiple output `DownChunkingPlugin`

- strax/context.py
- strax/plugins/__init__.py
- strax/plugins/exhaust_plugin.py
- strax/plugins/plugin.py
- tests/test_exhaust_plugin.py
It is useful when you want to load inputs together.
It is actually used here: https://github.com/dachengx/axidence/blob/e3acf58970d11d06b9ebb4830511cca408aa5d28/axidence/plugins/pairing/peaks_paired.py#L17
> Add `ExhaustPlugin` that exhausts all chunks when fetching data

- strax/chunk.py
- strax/context.py
- strax/plugins/overlap_window_plugin.py
- strax/plugins/plugin.py
- strax/storage/common.py
- tests/test_hyperruns.py
Hyperruns. Hyperruns are superruns, also processing of hyperruns depends on `run_metadata` defined similarly to https://straxen.readthedocs.io/en/latest/tutorials/SuperrunsExample.html#Define-a-superrun:.
If a hyperrun has run_id `__000000`, the `plugin.run_id` of the plugins used in processing will be `000000`, and the subruns of the hyperrun will be mixed(concatenated) while processing.
A new attribute `allow_hyperrun` of `strax.Plugin` class is added. The `allow_hyperrun` of `data_type` depends on the `data_type` whose `allow_hyperrun` is `True` can only be `True`. So this means, your father is `True`, so you must be `True`.
The key feature of hyperrun is that the chunks of subruns can …
> Implement Hyperrun

- strax/context.py
- tests/test_context.py
Add a function to return the collection of which `data_type` belongs to which `data_kind`.
[slack thread](https://xenonnt.slack.com/archives/C016UJZ090B/p1715695013285269)
Iterate through the `strax.Conetxt._plugin_class_registry` and init plugins by `strax.Conetxt.__get_plugin` to let `strax.Context` to assign the `data_kind`, then collect the results.
In the test, the function `get_data_kinds` will return:
```
({'records': ['records'], 'peaks': ['peaks', 'cut_peaks']}, {'records': 'records', 'peaks': 'peaks', 'cut_peaks': 'peaks'})
```
- Update …
> Add function to collect `data_type` and `data_kind`

- extra_requirements/requirements-tests.txt
- requirements.txt
Similar to https://github.com/XENONnT/cutax/pull/439, following https://github.com/XENONnT/base_environment/pull/1718.
Since numpy updated to 2.0.0 and sharedaray does not follow the updates timely, we see error like https://github.com/AxFoundation/strax/actions/runs/9726479771/job/26844965537?pr=849. To fix it, we assign a dedicated sharedarray version. It required `numpy<2.0.0`.
Please make sure that all automated …
> Patch sharedarray version due to numpy updating

- strax/chunk.py
This PR solves the error we see in straxen testing GitHub action: https://github.com/XENONnT/straxen/actions/runs/9516464741/job/26232816323
When the length of a chunk is zero, this line returns `False`:
https://github.com/AxFoundation/strax/blob/d92e64bd887bb6af7d71795ff4753a8174c8f5d6/strax/chunk.py#L448
Which is not intended. The intended behavior is to concatenate the cache and a new chunk if the cache is not None. This PR fix it.
- Does it solve one of the open …
> Fix cache of Rechunker, zero chunk is not None

- strax/context.py
Simple function to print the storage with `readonly=False`. It can be useful when you want to know which storage can be changed.
> Print writable storage

- strax/processors/post_office.py
- strax/processors/single_thread.py
When testing `SingleThreadProcessor`, run the codes below:
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import straxen
from straxen.test_utils import nt_test_run_id
st = straxen.test_utils.nt_test_context()
assert st.is_stored(nt_test_run_id, 'raw_records')
st.make(nt_test_run_id, 'event_info', processor='single_thread')
```
In `strax_test_data/012882-pulse_counts-exzzquvjyt_temp`, run `ls -lah`,
```
total 12K
drwxr-xr-x  2 xudc xudc 4.0K Jul  1 17:17 .
drwxrwxrwx 23 xudc xudc 4.0K Jul  1 17:18 ..
-rw-r--r--  1 xudc xudc 1.7K Jul  1 17:17 pulse_counts-exzzquvjyt-metadata.json
```
So no chunk is saved. This is because after a `topic` stops its iteration and if it is from a multiple output plugin like …
> Save multiple output when iteration stops in `PostOffice`

- strax/chunk.py
As title suggested. If still using `cache=True`, you will see errors like
```
Exception in thread load:event_se_density:
Traceback (most recent call last):
File "/opt/XENONnT/anaconda/envs/XENONnT_2024.03.1/lib/python3.9/threading.py", line 980, in _bootstrap_inner
self.run()
File "/opt/XENONnT/anaconda/envs/XENONnT_2024.03.1/lib/python3.9/threading.py", line 917, in run
self._target(*self._args, **self._kwargs)
File "/home/xudc/strax/strax/mailbox.py", line 290, in _send_from
self.close()
File "/home/xudc/strax/strax/mailbox.py", line 354, in close
self.send(StopIteration)
File "/home/xudc/strax/strax/mailbox.py", line 307, in send
raise MailboxKilled(self.killed_because)
strax.mailbox.MailboxKilled: (<class 'ValueError'>, …
```
> Do not cache numba decorated `split_array`

- strax/storage/common.py
This is helpful when you just want to process several chunks for testing.
`_chunk_number` will be propagated from `get_iter`: https://github.com/AxFoundation/strax/blob/bb23240c199276656fe9bd1dda7e9f5cf90bb127/strax/context.py#L1481
> Allow `_chunk_number` to be list or tuple

- strax/context.py
Fix https://github.com/AxFoundation/strax/issues/846
The reason this can work is explained here: https://github.com/AxFoundation/strax/pull/859#issue-2432793166
Remove duplicated targets when `get_iter`.
> Filter out duplicated targets in function `get_iter`

- strax/storage/common.py
It is very dangerous to change the `lineage` attribute of `DataKey` because it will make `lineage` and `lineage_hash` inconsistent.
So this PR makes sure they are assigned at the same time.
> Set `lineage` and `lineage_hash` simultaneously

- strax/context.py
- strax/run_selection.py
The `chunk_number` was passed to `Context.get_iter` to only load a specific chunk. But the previous implementation has weaknesses:
1. The `chunk_number` is not tracked by lineage so if you process twice with a different `chunk_number`, though the lineage is the same, the results are not.
2. Can not assign which `data_type` to load by chunk number.
This PR makes sure that the `chunk_number` is tracked by lineage, and you can assign which chunk to load which data_type.
This PR is designed following plan: https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:analysis:analysis_tools_team:sr2_processing. We will later make [outsource](https://github.com/XENONnT/outsource) more compatible with strax via this PR.
Depends on …
> Include `chunk_number` in lineage: Per chunk storage

- bin/rechunker
- strax/chunk.py
- strax/config.py
- strax/context.py
- strax/plugins/plugin.py
- strax/processing/general.py
- strax/processors/post_office.py
- strax/processors/single_thread.py
- strax/storage/common.py
- tests/test_storage.py
- tests/test_superruns.py
Previously, "rechunk" in strax is equivalent to merging. Say, data_type A depends on B. When the chunk of B is very large, inevitability A will be large and even larger than `target_size_mb`, which will make `target_size_mb` not working.
This PR allows the chunks to be split. It ALSO allows the chunks of superruns to be split, which might cause inconsistency, so I suggest a minor or even major bump.
TODOs:
- More tests need to be done to validate that the results are the same before and after the PR.
- Change straxen to inherit from `strax.chunk.DEFAULT_CHUNK_SPLIT_NS` instead of hardcoded `safe_break_in_pulses`.
There are several things changed to make this happen:
1. Return a list of …
> Allow splitting in rechunking

- strax/context.py
- strax/plugins/plugin.py
- strax/run_selection.py
- strax/storage/common.py
- strax/storage/files.py
- tests/test_superruns.py
The subruns of a superrun is not checked when loading a saved superrun after redefining the superrun. You will find the example in the MWE.
This PR does the following things:
1. Add an argument of `DataKey`: `subruns`, which is loaded from the metadata of superrun. Of course, if there is no metadata, an error will be raised.
2. Add `Context.get_datakey` for the context to get the decorated `DataKey`. Change all direct call of `strax.DataKey` in `Context` to `Context.get_datakey`, including `Context.key_for`.
3. Include the deterministic hash of `subruns` to the `run_id` in `DataKey`, so if everything is the same except `subruns`, the `DataKey.__repr__` will still change.
The motivation …
> Add subruns information in `DataKey` of superruns to track metadata

- strax/context.py
- strax/run_selection.py
- tests/test_core.py
- tests/test_superruns.py
Close https://github.com/AxFoundation/strax/issues/876.
The reason for this PR is in the issue description.
If `_combining_subruns` is `True`, only save the targeted `data_type`.
> Only save combined `data_type` in only-combining mode

- strax/context.py
- tests/test_context.py
- tests/test_core.py
- tests/test_down_chunk_plugin.py
- tests/test_superruns.py
Close https://github.com/AxFoundation/strax/issues/873
> Remove `get_meta` function from Context

- strax/context.py
- tests/test_superruns.py
> Show waring when the `chunk_number` is not needed

- strax/utils.py
- tests/test_utils.py
The deleted if statement is not really needed because `run_id_output` is always generated no matter `add_run_id_field` is `True` or `False`.
Close: https://github.com/AxFoundation/strax/issues/783
> Use `run_id_output` sorting `final_result` in `multi_run`

- strax/context.py
- strax/storage/common.py
- tests/test_superruns.py
To solve the caveat in https://github.com/AxFoundation/strax/pull/871, this PR saves the `combining` (True or False) in `strax.DataKey` to distinguish whether superrun is in only combining mode.
Also, change `_combining_subruns` to `combining` because it will be an argument frequently used.
PR first simplifies `get_components` and adds another attribute `combining` in `strax.DataKey`.
Please find the example at `test_only_combining_superruns` modified by this PR.
- …
> Add `combining` into the `DataKey`

- strax/context.py
- strax/utils.py
Close: https://github.com/AxFoundation/strax/issues/889
> Deprecate `selection_str`

- strax/context.py
- tests/test_context.py
You can use `st._get_plugins(targets=(data_type,), run_id=run_id)` to get the dependencies of `data_type`, but this is too complicated, we need a simplified `run_id` independent function.
> Add `run_id`  independent function to get the dependencies `datat_type`

- strax/context.py
- strax/utils.py
- tests/test_core.py
Pandas' data strucutres can contain any type of Python objects. Therefore, there should be no issues in having np.arrays as element of a Pandas DataFrame.
Currently, the implementation of the Pandas method to convert from strucutred arrays to Pandas DataFrames is not optimal (it just doesn't work well). While we wait for them to fix it, I propose a fix myself just for our code.
This PR adds a function to properly convert between Numpy's structured arrays and pandas' DataFrames, allowing the user to use the `get_df()` method on any data type.
The PR also adds a simple test in `test_core.py`. Further tests can be implemented if deemed necessary.
For each column in the strucutred array, the function `convert_structured_array_to_dataframe()` in `strax/utils.py` checks the dimensionality of …
> Allow get_df on all data_types

- strax/context.py
- strax/io.py
- strax/storage/files.py
- strax/storage/zipfiles.py
- tests/test_context.py
- tests/test_core.py
- tests/test_saving.py
- tests/test_storage.py
Copy the codes from `strax.Context.copy_to_frontend` to `strax.Context._get_target_sf` and `strax.Context._check_merge_per_chunk_storage_kwargs` and use then in `strax.Context.merge_per_chunk_storage`.
> Select targeted software frontend in a clever way

- strax/context.py
To make the lineage unchanged after merging per-chunk storage, we need to set `chunk_number` to `None` to keep lineage hash the same as non-per-chunk storage.
> Cancel usage of `chunk_number` if loading the whole dependency

- strax/context.py
- tests/test_core.py
- tests/test_superruns.py
Sometimes we want to know which plugin is higher in the dependency tree than another. This PR adds the `tree_levels` function of `Context`, which returns the dictionary containing relative information.
For Example, for a given class with Records, Peaks registered, the tree_levels will return:
```
{'records': {'level': 0, 'class': 'Records', 'index': 0, 'order': 0}, 'peaks': {'level': 1, 'class': 'Peaks', 'index': 0, 'order': 1}}
```
Go through the dependency tree and assign `level` for the `data_type`s first. The `level` of a `data_type` will be higher by at least 1 than its dependencies.
Then the `data_type`s will be sorted by `level`, `class`, and `index`. Where the `index` is the index …
> Add function of dependency level of `data_types`

- pyproject.toml
- strax/io.py
- strax/processing/peak_building.py
- strax/processing/peak_merging.py
Only https://github.com/XENONnT/outsource/pull/213 can not limit the usage of CPU because `zstd` and `blosc` by default will use as many as CPU on the machine.
This PR replaces `zstd` with `zstandard` and sets a one-thread constraint of `zstd` and `blosc`.
The reason for replacing `zstd` with `zstandard` is listed here: https://python-zstandard.readthedocs.io/en/latest/projectinfo.html#comparison-to-other-python-bindings and https://github.com/indygreg/python-zstandard/blob/e27f2f49f187f5f698e0a6004bee2aed80fe39e3/docs/projectinfo.rst?plain=1#L30.
I hope this will not make the previously compressed data unable to be decompressed.
**Can you give a minimal working example (or illustrate …
> Set single thread of zstd and blosc

- strax/processing/peak_splitting.py
Further fix of https://github.com/AxFoundation/strax/pull/867, otherwise you will get error like
```
Exception during processing, closing savers and reraising
Traceback (most recent call last):
File "/srv/pegasus.zCfx4lR9W/process.py", line 136, in <module>
main()
File "/srv/pegasus.zCfx4lR9W/process.py", line 106, in main
process(st, run_id, data_type, chunks)
File "/srv/pegasus.zCfx4lR9W/process.py", line 31, in process
st.make(
File "/srv/pegasus.zCfx4lR9W/.local/lib/python3.9/site-packages/strax/context.py", line 1755, in make
for _ in self.get_iter(
File "/srv/pegasus.zCfx4lR9W/.local/lib/python3.9/site-packages/strax/context.py", line 1646, in get_iter
generator.throw(e)
File …
```
> Set default `max_downsample_factor_waveform_start` as not `None`

- strax/context.py
- strax/processors/post_office.py
- strax/processors/single_thread.py
This is to solve the error when `processor = "single_thread"` in https://github.com/AxFoundation/strax/issues/903.
In the example of https://github.com/AxFoundation/strax/issues/903, after `st.make(nt_test_run_id, "peaklets", processor="single_thread")`, the `pulse_counts` is saved. So the loader will load this plugin because `peaklets` need `records` and `pulse_counts` are produced along with `records`. So `pulse_counts` is in `components.loaders`.
But before this PR, since `records` is also in `components.plugins`, https://github.com/AxFoundation/strax/blob/dca35457bea07b278e331b07fefb98cea842e60a/strax/processors/single_thread.py#L38 will register `pulse_counts` in the producer so this caused the bug.
**Can you briefly describe …
> Do not add producer that has been added by saver

- strax/processing/peak_merging.py
This PR is a follow-up of https://github.com/AxFoundation/strax/pull/867 adding the option to merge lone hits into the non-downsampled waveforms.
> Add option to merge `lone_hits` into `data_start`

- strax/processing/peak_building.py
Further, fix https://github.com/AxFoundation/strax/pull/867#discussion_r1797770537. As said in that conversation, People might misunderstand the non-downsampled `data_start` if they are zero.
> Save `data_start` even there is no downsampling

- strax/dtypes.py
- strax/processing/peak_building.py
- strax/processing/peak_merging.py
- strax/processing/peak_splitting.py
- tests/test_general_processing.py
`max_downsample_factor_waveform_start` is not strictly needed. We can use the following logic: if `store_in_data_start` is `False`, do not save the `data_start`.
Also, change `digitize_top` to `store_data_top`, `store_in_data_top` to `store_data_top` to unify the variable names.
> Remove `max_downsample_factor_waveform_start`, simplify the saving of `data_start`

- strax/dtypes.py
If the not downsampled sample length is less than 200, the length of `data_start` can not be 200 of course.
> Small fix of dtype description

- .github/workflows/pytest.yml
- HISTORY.md
- pyproject.toml
Otherwise, you will get an error like:
```
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
Can't have direct dependency: base_environment@                        
git+https://github.com/XENONnT/base_environment.git ; extra == "tests".
See https://packaging.python.org/specifications/core-metadata for more 
information.
```
> Exclude git repo from the package metadata for PyPI

- strax/io.py
- tests/test_storage.py
> Allow `chunk_number` to be list or tuple in `dry_load_files` function

- strax/processing/peak_building.py
- strax/processing/peak_splitting.py
This PR fixes some smaller problems related to the `data_start` handling in the `peaklets` building/ splitting. 
- The flag `store_data_start` was not passed to recursive calls of the peak splitter. As a result some `peaklets` had `data_start` always set to 0. 
- `peaklet["length']` is used in `store_downsampled_waveform` to select the part of the waveform that is stored in `data_start`. If the waveform is downsampled, `peaklet["length']` is overwritten. When saving  `data_start` we need to take the initial length of the peaklet not the downsampled length.
> Fixing store_data_start in recursive peak splitter calls and peaklet["length'] fix in store_downsampled_waveform

- strax/plugins/plugin.py
To save memory usage. This function is turned off by default but will only be used for the memory-heavy plugins.
> Run garbage collection after yield result in `Plugin.iter`

- strax/context.py
- strax/processing/peak_merging.py
- strax/run_selection.py
This PR just adds a safeguard.
If we do need to handle the case where peaks overlap, we need to change two lines:
1. https://github.com/AxFoundation/strax/blob/dd62b13bff1279cbf9683649e93b04f537d0f41c/strax/processing/peak_merging.py#L44, we can not assume `last_peak` has the largest `endtime`
2. https://github.com/AxFoundation/strax/blob/dd62b13bff1279cbf9683649e93b04f537d0f41c/strax/processing/peak_merging.py#L80, should change `=` to `+=`
> Raise error when peaks overlapping in `merge_peaks`

- strax/utils.py
If field `fn` is not in `result`, do not assign it.
> Fix a small bug in `merge_arrs`

- strax/utils.py
Because a lot of packages are using it.
Preparing for https://github.com/XENONnT/straxen/issues/1491.
> Move `set_nan_defaults` from straxen to strax

- strax/processing/peak_properties.py
Besides moving, two small changes are made:
1. add `dt / 2` to `center_time`
2. add `time` in the function (so `center_time` should be `np.int64`)
> Move `compute_center_times` from straxen to strax

- strax/processing/peak_properties.py
Just a minor improvement.
If using the previous approach, the `center_time` will be first converted to float then int. But the large `time` might cause the numerical error.
Following https://github.com/AxFoundation/strax/pull/938
> First concert to int then add float to keep precision

- strax/plugins/cut_plugin.py
- strax/processing/hitlets.py
- strax/processing/peak_splitting.py
- strax/processing/pulse_processing.py
- strax/run_selection.py
- tests/test_context.py
Because numpy already supports them.
But still use `np.bool_` in numba decorated function.
> Use `bool` instead of `np.bool_`

- strax/dtypes.py
- strax/processing/peak_building.py
- strax/processing/peak_merging.py
- strax/processing/peak_properties.py
- strax/processing/peak_splitting.py
- tests/test_peak_processing.py
- tests/test_peak_properties.py
Add `area_fraction_top`, `center_time`, and `median_time` to `peak_dtype`. They will be calculated by `compute_properties`.
> Calculate `area_fraction_top`, `center_time` and `median_time` at peaklet level

- strax/chunk.py
- strax/plugins/overlap_window_plugin.py
- strax/plugins/plugin.py
This will lower the memory usage of `st.make(run_id, 'peaklets')` of XENONnT by 1 / 6, if set `clean_chunk_after_compute = True`.
Note: https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:straxen:optimize_outsource_resources#optimized_memory_usage
> Delete input chunks after compute method to save memory

- strax/processing/peak_building.py
- strax/processing/peak_merging.py
`t0 = records[hits["record_i"]]["time"]` and `dt = records[hits["record_i"]]["dt"]` will create a temporary array that takes a lot of memory.
> Reduce RAM usage of `find_hit_integration_bounds`

- strax/processing/data_reduction.py
- strax/processing/general.py
- strax/processing/hitlets.py
- strax/processing/peak_building.py
- strax/processing/peak_merging.py
- strax/processing/peak_properties.py
- strax/processing/peak_splitting.py
- strax/processing/pulse_processing.py
- strax/processing/statistics.py
Also `@numba.jit(nopython=True, nogil=True, cache=True)` to `@numba.njit(nogil=True, cache=True)`.
> Numbafy `merge_peaks`

- strax/processing/peak_merging.py
To solve errors in https://github.com/XENONnT/straxen/actions/runs/12668685734/job/35309542822?pr=1513
```
Rejected as the implementation raised a specific error:
NumbaTypeError: Unsupported array index type unicode_type in [unicode_type]
raised from /opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/numba/core/typing/arraydecl.py:104
- Of which 1 did not match due to:
Overload in function 'SetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 221.
With argument(s): '(unaligned array(Record(Start time since unix epoch [ns][type=int64;offset=0;title=Start time since unix epoch [ns]],time[type=int64;offset=0;title=Start time since unix epoch [ns]],Length of the interval in samples[type=int32;offset=8;title=Length of the interval in …
```
> Fix bug of numbafied `merge_peaks`

- strax/context.py
- strax/run_selection.py
Otherwise, you will see
```
/home/xudc/strax/strax/run_selection.py:196: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
docs = pd.concat([docs, new_docs[~np.in1d(new_docs["name"], docs["name"])]], sort=False)
```
> Do not concatenate empty dataframes

- strax/processing/peak_merging.py
endtime != time + length * dt because of the downsampling after merging, so we have to collect the endtime in `_merge_peaks`.
> Collect `endtime` from `_merge_peaks` function

- strax/chunk.py
- strax/context.py
- strax/plugins/overlap_window_plugin.py
- strax/processing/peak_merging.py
- strax/utils.py
- tests/test_overlap_plugin.py
Close: https://github.com/AxFoundation/strax/issues/919
The implementation is straightforward. When a plugin provides multiple outputs, the outputs will be truncated at the same `t` and cached. The caching of input and output can use the same function in this PR: `cache_beyond`.
> `OverlapWindowPlugin` support multiple outputs

- strax/chunk.py
- strax/context.py
- tests/test_superruns.py
This is a bug fix for https://github.com/AxFoundation/strax/pull/871.
Do not allow `save` in `combining` mode.
> When loader is available, do not save anything

- strax/context.py
- strax/plugins/exhaust_plugin.py
- strax/plugins/plugin.py
Then the `chunk_i` argument will be correct for `Plugin.compute`.
> Set `chunk_number` as attribute of `Plugin` to pass `chunk_i`

- strax/utils.py
Otherwise, weirdly you will see
`peaklets = st.get_array(run_id, targets=('peaklets', 'peaklet_classification'))` but `peaklets['type']` is always 0 (from `"peaklets"`).
This error might happen at https://github.com/AxFoundation/strax/blob/4e13c7a55e033758071f9092dd83c57868fa36c3/strax/context.py#L1823.
> Force memory allocation in `merge_arrs`

- strax/context.py
- strax/utils.py
And revert https://github.com/AxFoundation/strax/pull/957.
Otherwise, weirdly you will see
`peaklets = st.get_array(run_id, targets=('peaklets', 'peaklet_classification'))` but `peaklets['type']` is sometimes 0 (from `"peaklets"`).
> Temporary plugin should keep order of targets

- strax/context.py
- strax/plugins/plugin.py
- strax/storage/common.py
- strax/storage/files.py
This PR rechunks the `depends_on` for better performance on memory usage.
Corner cases:
`compute_takes_chunk_i == True` and `chunk_number` is provided: this is not allowed, because otherwise loaded chunks stop earlier than the expected time.
Similar to https://github.com/AxFoundation/strax/pull/865
> Allow `depends_on` rechunking

- strax/io.py
Streaming decompression can significantly reduce memory usage of `bz2` and `lz4`. To keep backward compatibility, the `decompress` key is kept. The memory-reduced function is assigned to `_decompress` key.
> Save memory when decompressing data

- .github/workflows/pytest.yml
- pyproject.toml
- strax/io.py
Following https://github.com/AxFoundation/strax/pull/976
The zstd is still used when compressing data, because zstandard's compression is multithreaded.
> Use `zstandard` to decompress chunks to save memory

- strax/chunk.py
- strax/storage/common.py
Previously, if another possible split is too far away from the last available split, the while loop would never stop.
> Prevent infinite loop in `get_splits`

- strax/io.py
Without the fix, an error about no `data` will be raised.
> Fix a corner case where the chunk size is zero

- strax/context.py
- tests/test_core.py
The yield results would be saved: https://github.com/AxFoundation/strax/blob/40777da3bffd2054583c997402ca623bf782a784/strax/context.py#L1679 without this PR.
> Do not initialize any saver when dropping columns

- strax/chunk.py
The chunks that got merged take the value from the last appearance of the field. E.g. if `depends_on = ("peaklets", "peaklet_classification")`, the `"type"` of merged data will take the `"type"` of `"peaklet_classification"`.
> Add more comments about `merge_arrs`

- strax/context.py
The dependency structure forms a directed acyclic graph (DAG), allowing us to define a topological level for each node, as implemented in https://github.com/AxFoundation/strax/pull/896. This new PR extends that by also computing the shortest dependency path within the DAG:
1. Topological level: `level(node) = 1 + max(level(dep))` Represents the longest path from any source node to the given node — useful for understanding how late a node occurs in the dependency chain.
2. Shortest dependency path: `level(node) = 1 + min(level(dep))` Captures the minimum number of steps from a source node to the current node, identifying the shallowest point of dependency.
By combining both metrics, we can better analyze the structure of the …
> Topological level and shortest dependency path of dependency tree (directed acyclic graph)

- strax/processors/post_office.py
Before this PR, when running:
```
import fuse
run_id = '058169'
st = fuse.xenonnt_fuse_full_chain_simulation(corrections_run_id=run_id)
for data_type in ['microphysics_summary', 'drifted_electrons', 'extracted_electrons', 's2_photons_sum', 'photo_ionization_electrons']:
st.make(run_id, data_type, save=data_type)
```
got error:
```
...
File "/home/xudc/strax/strax/processors/post_office.py", line 204, in _read
result = self._fetch_new(topic)
^^^^^^^^^^^^^^^^^^^^^^
File "/home/xudc/strax/strax/processors/post_office.py", line 261, in _fetch_new
assert isinstance(msg, dict)
AssertionError
```
This PR fixes this.
The dependency tree looks like this
And `s2_photons` is not saved because its `save_when` is not `ALWAYS`. When `data_type` …
> Do not assign `_multi_output_topics` when the topic is from a loader

- strax/context.py
- strax/plugins/plugin.py
- tests/test_core.py
```
import straxen  # e9fe5dd7fb61fb537d35732730b41639ebc39980
import saltax  # e100810ad106351ef1180499889257d59c97ed90
st = saltax.contexts.sxenonnt(
saltax_mode="salt",
generator_name="ybe",
recoil=0,
rate=10,
simu_mode="all",
simulation_config="sr2_dev",
corrections_version="global_v18",
output_folder="strax_data",
)
run_id = "047967"
st.is_stored(run_id, "peaklets", chunk_number={"raw_records": [0, 1, 2]})
```
First get the efficiency of the above codes:
```
python -m cProfile -o output.prof test_chunks.py
gprof2dot -f pstats output.prof | dot -Tsvg -o profile.svg
```
The most significant part is
This is because when `chunk_number` is not None, strax before this PR will not cache plugins, so every time building the lineage of …
> Better performance lineage `chunk_number` assignment
