AxFoundation/strax

.travis.yml
This is me improving the TravisCI settings in the following ways:
1.  Documentation
2. Adding OSX testing
3. Using miniconda for providing finer control over Python versions
4. Using matrix builds to allow finer testing in the future (Python versions, numba versions, OS, etc)
miniconda is not required to install strax, but makes testing a lot easier.  You will want to squash merge this since it took 10s of tries to get it actually working on TravisCI.
=> Better TravisCI settings

strax/storage/common.py
Closes #67 
Added: self.log = logging.getLogger(self.__class__.__name__)
=> Fix missing logger

strax/dtypes.py, strax/processing/peak_building.py, strax/utils.py
Fixed merging dtypes, the wrong area calculation and added saturated channels
=> Fix merging of dtypes and adding number of saturated channels to peaks

strax/processing/peak_building.py
Small fix to account for the sample number - time (ns) factor missing
=> Bugfix in sum_waveform

strax/plugin.py, tests/test_core.py
... and raise a custom exception if not.
=> Check plugins produce correct dtype

strax/processing/peak_splitting.py, tests/test_peak_splitting.py
Hi!
I went through the code of LocalMinimumSplitter and I tried to come up with a unit test for it. This is the result of me trying. I hope it helps in some way:
The code takes arbitrary settings to check against and the assert statements check if the result of the mimicked peak are allowed by the logic behind LocalMinimumSplitter.
Cheers,
Tim
=> Peak splitting

strax/processing/general.py
=> Added comment to overlap_indices()

strax/processing/peak_splitting.py
Motivated by Jelle's straxferno course, I just edited what I think was a tiny typo in the NaturalBreaksSplitter docstring. For fun I added a little PeakSplitter docstring too, then saw that @jorana signed up for that one so I put him to review so he can edit it as he likes :)
Edit: I'm not allowed to request a review heheh, but I @'ed him so that should do the trick.
=> Update peak_splitting.py docs

strax/context.py
Fix some missing f strings and unused variable.
I was already wondering about this when preparing for circle 8 but I just noticed that it is an assignment for:
https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:aalbers:straxferno#circle_8processing_initialization
=> Fix fstrings and remove an unused variable

strax/context.py, tests/test_core.py
Fix issue #295 where the progress-bar raises an error if disabled as start_time is not defined.
Relates to https://github.com/AxFoundation/strax/pull/276 where the progress bar was introduced.
=> Small progress-bar bug fix

strax/processing/hitlets.py
Solves issue https://github.com/AxFoundation/strax/issues/328 for the conditional_entropy.
=> Fixing _conditional_entropy does not modifiy hitlet data.

strax/plugin.py, strax/storage/mongo.py, strax/storage/s3.py
Add docstrings where needed.
Fixes https://github.com/AxFoundation/strax/issues/313 (partially)
Fixes https://github.com/AxFoundation/strax/issues/330 (sufficiently)
Initializes #307 for S3 frontend
=> Update documentations and adress issues

strax/corrections.py
Keep either self.client or self.database so as not to confuse which is used.
=> Keep self.database or self.client, not both

strax/plugin.py
Update of print statement object ids can be confused with unix times.
=> More clear print statement.

requirements.txt
The requirement is too strict now.
=> Fix numpy deps

requirements.txt
Remove from requirements  as s3 backend is not used
=> Cleanup requirements for boto3

strax/processing/peak_building.py
Patch PR for #420 , fix max-length now that int32 and allow long peaks for find_peak_groups
=> quick fix for find_peak_groups

.travis.yml
Testing is failing since ztsd 1.5 is not being installed properly, grep the right version from the base env.
=> Use zstd for from base-env for testing

.travis.yml, requirements.txt
Relax the requirements for zstd again now that version 1.5.0.2 is out
=> Relax zstd requirements again

.github/workflows/pytest.yml, .github/workflows/tests.yml, .travis.yml, README.md
=> Tweak #454

strax/run_selection.py, strax/testutils.py, tests/test_hitlet.py, tests/test_peak_splitting.py, tests/test_utils.py
Remove some additional numpy DeprecationWarnings.
=> Reduce numpy warnings

strax/plugin.py
=> Parallel plugin timeout

strax/context.py
Fix an old function causing https://github.com/XENONnT/straxen/pull/666
=> Remove context.apply_selection

.github/workflows/pytest.yml
See https://github.com/XENONnT/straxen/pull/772
=> cache deps

requirements.txt
See https://github.com/XENONnT/straxen/issues/782
=> Require pymongo 3.*

.gitattributes
See https://github.com/XENONnT/straxen/pull/838, we have now a mix of linux and windows line endings, it's better to unify this
=> fix line endings

strax/processing/pulse_processing.py
Remove a small deprecated function no longer in use
=> remove deprecated function

extra_requirements/requirements-tests.txt
=> Numba 0.55

.github/workflows/pytest.yml
If we test with straxen's master, we should also run it's code
=> Fix testing from straxen

strax/run_selection.py
=> Small fix superruns define run

.coveragerc
Add a small config file for testing
=> ignore raises on testing for coverage

tests/test_inline_plugin.py
Add some extra test for the inline plugin3
I was acually trying to test something like #674 but Daniel beat me, nevertheless it's good to have this inlined tests
=> add test for inline plugin

strax/processing/peak_merging.py
These fields are `tight_coincidence` `max_gap` `max_goodness_of_split` `max_diff` `min_diff`
=> Save other fields in the merged peaks to their default value

strax/processing/general.py
Two small modifications:
1. Little update to structure the time/endtime testing a bit. 
2. Small fix to allow for overlapping containers in touching windows.
=> Check sorted update

extra_requirements/requirements-docs.txt, extra_requirements/requirements-tests.txt
Small changes on the version of dependencies.
=> Update version of urllib3, remove version control of deepdiff

strax/chunk.py, strax/run_selection.py, strax/storage/files.py, strax/storage/mongo.py, strax/storage/zipfiles.py, tests/test_storage.py
Check the size of chunk when loading data.
Add a decorator `check_chunk_n` for `strax.StorageBackend._read_chunk`.
=> Check chunk size right after loading chunk

extra_requirements/requirements-docs.txt
Fix error like: https://readthedocs.org/projects/strax/builds/23936517/
=> Specifically install lxml_html_clean

.github/workflows/pytest.yml
Following https://github.com/XENONnT/straxen/pull/1353
=> Install `graphviz` for the pytests

strax/run_selection.py
=> Disable tqdm progress bar when `check_available` is empty

strax/plugins/plugin.py
=> Tiny change on the trailing space

strax/context.py, strax/plugins/cut_plugin.py
=> Add `register_cut_list`

strax/run_selection.py
=> Check `include_tags` and `exclude_tags`

strax/mailbox.py, strax/storage/files.py
=> Minor error message fix

strax/storage/files.py
Just save run metadata in a format where indent is 4.
=> Save run metadata in better format

strax/context.py, tests/test_core.py, tests/test_superruns.py
=> Add more tests about `PostOffice` and `get_components`

strax/context.py, strax/run_selection.py, tests/test_core.py
The reason for this PR is described at https://github.com/AxFoundation/strax/issues/875.
Close https://github.com/AxFoundation/strax/issues/874
Close https://github.com/AxFoundation/strax/issues/875
=> Prohibit `chunk_number` for `LoopPlugin` and `OverlapWindowPlugin`

.pre-commit-config.yaml, pyproject.toml, strax/__main__.py, strax/scripts/rechunker.py
1. Move `rechunker` to `strax/scripts/rechunker.py`
2. Remove `bin/` folder because it is incompatible with `pyproject.toml`
3. Add script of `rechunker` to `pyproject.toml`
=> Fix the usage of scripts

strax/processing/peak_merging.py
Solve https://github.com/AxFoundation/strax/issues/906
=> Propagate n_top_channels to _add_lone_hits

strax/dtypes.py, strax/processing/pulse_processing.py
Close: https://github.com/XENONnT/straxen/issues/1360
=> Add `max_time` which is the time when hit reaches its maximum

strax/context.py, tests/test_context.py
Just a simple function, will be useful when calculating potential storage usage.
=> Add a function to get size of a single item of data_type in bytes

strax/context.py
If you want all the dependencies, you do not need to initiate the plugin thoroughly.
=> Speed up `get_dependencies`

strax/io.py, strax/utils.py
The `kwargs` are the same to `apply_selection`.
=> Add more kwargs to `dry_load_files`

strax/io.py
You can still disable it by `disable=True`.
=> Print progress bar in `dry_load_files`

strax/processing/peak_merging.py
It seems sometimes numba does not like the `endtime` flag.
=> Fix `merge_peaks` by removing `endtime` assignment

strax/dtypes.py, strax/processing/peak_merging.py, strax/processing/peak_splitting.py
The new features provide more detailed information of the time-space distribution in parse S1.
=> First and last channel inside peak(let)s

strax/processing/peak_properties.py
Very small change for corner cases.
=> Some times the sum of data is zero due to numerical inaccuracy

strax/context.py
Designed for https://github.com/XENONnT/straxen/pull/1546
=> Add a flag indicating whether check subruns' configs

.github/workflows/pytest.yml, strax/context.py
Reverts AxFoundation/strax#964
Depends on https://github.com/XENONnT/straxen/pull/1548
This is unnecessary, and we should do all context modification in straxen - one place.
=> Revert "Add a flag indicating whether check subruns' configs"

strax/plugins/overlap_window_plugin.py
I forgot to push the needed changes to the last https://github.com/AxFoundation/strax/pull/970.
=> Push the latest change

.github/workflows/pytest.yml, pyproject.toml, strax/io.py
Reverts AxFoundation/strax#977
=> Revert "Use `zstandard` to decompress chunks to save memory"

strax/storage/common.py
The wrong implementation was introduced in 34cbe535ad39a01441e00695bef07fcf35b396ec. The memory usage before this PR is 
. After the PR, it is
=> Prevent unnecessary reference to chunks

.github/workflows/pytest.yml, pyproject.toml, strax/io.py
Reverts AxFoundation/strax#978
=> Revert "Revert "Use `zstandard` to decompress chunks to save memory""

strax/plugins/plugin.py
This is a simple check to make sure that the `data_type` of the returned chunk is as promised.
=> Check the `data_type` of returned chunk of plugin
